FROM touchvie/tomcat8-jdk8
COPY war/retail-*.war /usr/local/tomcat/webapps/
COPY war/*.jar /usr/local/tomcat/lib/
COPY war/server.xml /user/local/tomcat/conf
COPY war/context.xml /user/local/tomcat/conf
