
USE [master]
GO

/****** Object:  Database [RETAIL]    ******/
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'RETAIL')
	DROP DATABASE [RETAIL]
GO

/****** Object:  Database [RETAIL]   ******/
CREATE DATABASE [RETAIL] ON  PRIMARY
( NAME = N'RETAIL_Data', FILENAME = N'D:\RETAIL_DB\DATA\RETAIL.mdf' , SIZE = 6528KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON
( NAME = N'RETAIL_Log', FILENAME = N'D:\RETAIL_DB\\DATA\RETAIL.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE Latin1_General_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'RETAIL', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RETAIL].[dbo].[sp_fulltext_database] @action = 'disable'
END
GO
ALTER DATABASE [RETAIL] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [RETAIL] SET ANSI_NULLS OFF
GO
ALTER DATABASE [RETAIL] SET ANSI_PADDING OFF
GO
ALTER DATABASE [RETAIL] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [RETAIL] SET ARITHABORT OFF
GO
ALTER DATABASE [RETAIL] SET AUTO_CLOSE ON
GO
ALTER DATABASE [RETAIL] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [RETAIL] SET AUTO_SHRINK ON
GO
ALTER DATABASE [RETAIL] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [RETAIL] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [RETAIL] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [RETAIL] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [RETAIL] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [RETAIL] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [RETAIL] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [RETAIL] SET  DISABLE_BROKER
GO
ALTER DATABASE [RETAIL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [RETAIL] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [RETAIL] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [RETAIL] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [RETAIL] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [RETAIL] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [RETAIL] SET  READ_WRITE
GO
ALTER DATABASE [RETAIL] SET RECOVERY SIMPLE
GO
ALTER DATABASE [RETAIL] SET  MULTI_USER
GO
ALTER DATABASE [RETAIL] SET PAGE_VERIFY TORN_PAGE_DETECTION
GO
ALTER DATABASE [RETAIL] SET DB_CHAINING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

/****** Object:  Login [SPIDBUser]   ******/
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'RETAILUser')
CREATE LOGIN [RETAILUser] WITH PASSWORD=N'RETAILUser', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [RETAIL]
GO

/****** Object:  User [SPIDBUser]   ******/
CREATE USER [RETAILUser] FOR LOGIN [RETAILUser] WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember @rolename=[db_owner], @membername=[RETAILUser]
GO
