CREATE TABLE COMPANY_CONTACT(
                                COMP_CONTACT_ID BIGINT UNIQUE AUTO_INCREMENT NOT NULL,
                                COMP_ID BIGINT  NOT NULL,
                                CONTACT_ID BIGINT  NOT NULL
);

alter table COMPANY
    ADD COMP_DESC VARCHAR(1000) NULL,
    ADD COMP_LOGO BLOB NULL,
    ADD COMP_PIC BLOB NULL,
    ADD COMP_CODE VARCHAR(100) NULL,
    ADD CONTACT_ID BIGINT NULL #CONTACT INFORMATION OF COMPANY
;
ALTER TABLE COMPANY ADD CONSTRAINT COMPANY_CONTACT_ID_2CONTACT_FK FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);

ALTER TABLE COMPANY_CONTACT ADD CONSTRAINT COMPANY_CONTACT_FK1 FOREIGN KEY (COMP_ID) REFERENCES COMPANY(COMP_ID);

ALTER TABLE COMPANY_CONTACT ADD CONSTRAINT COMPANY_CONTACT_FK2 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);


INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION, COLOR) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='CONTACT_TYPE'),'CONTACT_TYPE_OWNER', 'OWNER', 'OWNER','amber');
;

CREATE TABLE CONTACT(
                        CONTACT_ID BIGINT UNIQUE AUTO_INCREMENT NOT NULL,
                        Title varchar(10) NULL,
                        First_Name varchar(100) NULL,
                        Sur_Name varchar(100) NULL,
                        Middle_Name varchar(100) NULL,
                        COUNTRY varchar(100) NULL,
                        STATE varchar(100) NULL,
                        SUBURB varchar(100) NULL,
                        POST_CODE varchar(20) NULL,
                        ADDRESS1 varchar(200) NULL,
                        ADDRESS2 varchar(200) NULL,
                        E_MAIL varchar(100) NULL,
                        E_MAIL2 varchar(100) NULL,
                        MOBILE varchar(20) NULL,
                        PHONE varchar(20) NULL,
                        FAX varchar(20) NULL,
                        WEB_SITE nchar(100) NULL,
                        CONTACT_TYPE BIGINT
);


##KIAN BREAD COMPANY CONTACT INFO
INSERT INTO CONTACT (COUNTRY, STATE, SUBURB, POST_CODE, ADDRESS1, ADDRESS2, E_MAIL, MOBILE, PHONE, FAX, WEB_SITE) VALUES ('AUSTRALIA', 'NSW', 'THE PONDS','2769', '5 KATOOMBA STREET', '','KIANBREAD@GMAIL.COM','0466554294','8876543','','www.kianbread.com.au');
#### DEFINE KIANBREAD COMPANY
INSERT INTO COMPANY(COMP_NAME, COMP_DESC, CONTACT_ID) values ('KIAN BREAD SUPERMARKET', 'KIAN BREAD supermarket established in 2010',(select max(contact_id) from contact));
;
##KIAN BREAD OWNER CONTACT INFO
INSERT INTO CONTACT (TITLE, First_Name, Sur_Name, Middle_Name,COUNTRY, STATE, SUBURB, POST_CODE, ADDRESS1, ADDRESS2, E_MAIL, MOBILE, PHONE, FAX, WEB_SITE, CONTACT_TYPE) VALUES ('MR','REZA','OMIDI','NAKHJAVAN','AUSTRALIA', 'NSW', 'THE PONDS','2769', '5 KATOOMBA STREET', '','KIANBREAD@GMAIL.COM','0466554294','8876543','','www.kianbread.com.au', (SELECT CATEGORY_ID FROM CONFIG_CATEGORY WHERE CATEGORY_CODE = 'CONTACT_TYPE_OWNER'));
INSERT INTO COMPANY_CONTACT(COMP_ID, CONTACT_ID) VALUES ((SELECT COMP_ID FROM COMPANY WHERE COMP_NAME='KIAN BREAD SUPERMARKET'), (SELECT MAX(CONTACT_ID) FROM CONTACT))


