USE RETAIL
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('A', 'COST + 20.00%', 'COST + 20.00%','20.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('B', 'COST + 23.00%', 'COST + 23.00%','23.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('C', 'COST + 28.00%', 'COST + 28.00%','28.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('D', 'COST + 38.00%', 'COST + 38.00%','38.00')
GO

INSERT INTO CONFIG_TYPE(CONFIG_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ('SUPPLIER_TYPE', 'SUPPLIER TYPE', 'SUPPLIER TYPE');
GO

INSERT INTO CONFIG_TYPE(CONFIG_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ('SUPPLIER_STATUS', 'SUPPLIER STATUS', 'SUPPLIER STATUS');
GO


INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='SUPPLIER_TYPE'),'SUPPLIER_TYPE_DIRECT', 'DIRECT', 'DIRECT');
GO


INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='SUPPLIER_TYPE'),'SUPPLIER_TYPE_WAREHOUSET', 'WareHouse', 'WareHouse');
GO


INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='SUPPLIER_STATUS'),'SUPPLIER_STATUS_ACTIVE', 'Active', 'Active');
GO


INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='SUPPLIER_STATUS'),'SUPPLIER_STATUS_HELD', 'Held', 'Held');
GO

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='SUPPLIER_STATUS'),'SUPPLIER_STATUS_DELETED', 'Deleted', 'Deleted');
GO
