USE RETAIL
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('A', 'COST + 20.00%', 'COST + 20.00%','20.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('B', 'COST + 23.00%', 'COST + 23.00%','23.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('C', 'COST + 28.00%', 'COST + 28.00%','28.00')
GO

INSERT INTO CUSTOMER_GRADE(GRADE_CODE, GRADE_NAME, DESCRIPTION, RATE) VALUES ('D', 'COST + 38.00%', 'COST + 38.00%','38.00')
GO

INSERT INTO SEQUENCE(SEQ_NAME, NEXT_VAL) VALUES ('CUSTOMER_SEQ',0)
GO

INSERT INTO SEQUENCE(SEQ_NAME, NEXT_VAL) VALUES ('CUSTOMER_GRADE',0)
GO