use [retail]
go

alter table purchase_line add POL_QTY_RESERVED DECIMAL(31,4)
go

--PHYSICAL LOCATION OF STOCK.
CREATE TABLE STOCK_LOCATION(
    STCK_LOCN_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    STCK_LOCN_CODE VARCHAR(100) NULL,
    STCK_LOCN_NAME VARCHAR(100) NULL,
    STCK_LOCN_ADDRESS VARCHAR(500) NULL,
    ORGU_ID DECIMAL(31,0),
    STORE_ID DECIMAL(31,0)
);

CREATE TABLE STOCK(
    STCK_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    SUPPLIER_ID DECIMAL(31,0) NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRGP_ID DECIMAL(31,0),
    SELC_ID DECIMAL(31,0),
    ORGU_ID_LOCATION DECIMAL(31,0) NOT NULL,
    STCK_QTY DECIMAL(31,4) NOT NULL,
    UNOM_ID DECIMAL(31,0),
    STCK_COND DECIMAL(31,0) NOT NULL,
    STCK_CAT DECIMAL(31,0) NOT NULL,
    STCK_LOCN_ID DECIMAL(31,0),
    ORGU_ID_RESPBILITY DECIMAL(31,0),
    STCK_VALUE DECIMAL(31,6),
    STCK_LAST_VERIFIED datetime,
    LEGT_ID DECIMAL(31,0)
);

CREATE TABLE STOCK_EVENT(
    STCK_EVNT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    STCK_ID DECIMAL(31,0) NOT NULL,
    ORGU_ID DECIMAL(31,0),
    STORE_ID DECIMAL(31,0),
    USR_ID DECIMAL(31,0),
    SUPPLIER_ID DECIMAL(31,0) NULL,
    UNOM_ID DECIMAL(31,0),
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRGP_ID DECIMAL(31,0),
    SELC_ID DECIMAL(31,0),
    STCK_EVNT_DATE datetime,
    TXN_DATE datetime,
    TXN_TYPE DECIMAL(31,0),
    TXN_HEADER DECIMAL(31,0),
    TXN_LINE DECIMAL(31,0),
    TXN_NUMBER VARCHAR(100),
    STCK_LOCN_ID DECIMAL(31,0),
    STCK_QTY DECIMAL(31,4) NOT NULL,
    SELL_PRICE DECIMAL(31,6),
    COST_PRICE DECIMAL(31,6),
    STCK_COND DECIMAL(31,0),
    STCK_CAT DECIMAL(31,0)
);


ALTER TABLE STOCK_LOCATION
 ADD  CONSTRAINT STOCK_LOCATION_PK PRIMARY KEY(STCK_LOCN_ID);
GO

ALTER TABLE STOCK
 ADD  CONSTRAINT STOCK_PK PRIMARY KEY(STCK_ID);
GO

ALTER TABLE STOCK_EVENT
 ADD  CONSTRAINT STOCK_EVENT_PK PRIMARY KEY(STCK_EVNT_ID);
GO

ALTER TABLE STOCK_LOCATION ADD CONSTRAINT STOCK_LOCATION_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_LOCATION ADD CONSTRAINT STOCK_LOCATION_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK2 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK4 FOREIGN KEY (ORGU_ID_LOCATION) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK5 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK6 FOREIGN KEY (STCK_COND) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK7 FOREIGN KEY (STCK_CAT) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK8 FOREIGN KEY (STCK_LOCN_ID) REFERENCES STOCK_LOCATION(STCK_LOCN_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK9 FOREIGN KEY (ORGU_ID_RESPBILITY) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK1 FOREIGN KEY (STCK_ID) REFERENCES STOCK(STCK_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK4 FOREIGN KEY (USR_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK5 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK8 FOREIGN KEY (TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK9 FOREIGN KEY (STCK_COND) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK10 FOREIGN KEY (STCK_CAT) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK12 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK14 FOREIGN KEY (STCK_LOCN_ID) REFERENCES STOCK_LOCATION(STCK_LOCN_ID);
go

CREATE INDEX STOCK_LOCATION_IDX1 ON STOCK_LOCATION
(STCK_LOCN_NAME)
go

CREATE INDEX STOCK_IDX1 ON STOCK
(PROD_ID)
go

CREATE INDEX STOCK_IDX2 ON STOCK
(ORGU_ID_LOCATION)
go


CREATE INDEX STOCK_IDX3 ON STOCK
(STCK_COND)
go

CREATE INDEX STOCK_IDX4 ON STOCK
(STCK_CAT)
go

CREATE INDEX STOCK_IDX5 ON STOCK
(STCK_LOCN_ID)
go


CREATE INDEX STOCK_EVENT_IDX1 ON STOCK_EVENT
(STCK_ID)
go

CREATE INDEX STOCK_EVENT_IDX2 ON STOCK_EVENT
(ORGU_ID)
go

CREATE INDEX STOCK_EVENT_IDX3 ON STOCK_EVENT
(STORE_ID)
go

CREATE INDEX STOCK_EVENT_IDX4 ON STOCK_EVENT
(USR_ID)
go

CREATE INDEX STOCK_EVENT_IDX5 ON STOCK_EVENT
(PROD_ID)
go

CREATE INDEX STOCK_EVENT_IDX6 ON STOCK_EVENT
(STCK_EVNT_DATE)
go

CREATE INDEX STOCK_EVENT_IDX7 ON STOCK_EVENT
(TXN_DATE)
go

CREATE INDEX STOCK_EVENT_IDX8 ON STOCK_EVENT
(TXN_TYPE)
go

CREATE INDEX STOCK_EVENT_IDX9 ON STOCK_EVENT
(TXN_NUMBER)
go

CREATE INDEX STOCK_EVENT_IDX10 ON STOCK_EVENT
(STCK_COND)
go

CREATE INDEX STOCK_EVENT_IDX11 ON STOCK_EVENT
(STCK_CAT)
go


-------------------------------------- data -------------------------------------------
----- data ----

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='TXN_TYPE'),'TXN_TYPE_GOODS_IN', 'GOODS IN', 'GOODS IN');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='TXN_TYPE'),'TXN_TYPE_GOODS_RESERVE', 'GOODS RESERVED', 'GOODS RESERVED');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='TXN_TYPE'),'TXN_TYPE_GOODS_CANCEL_RESERVE', 'RESERVED CANCELED', 'GOODS RESERVED CANCELED');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='TXN_TYPE'),'TXN_TYPE_GOODS_IN_TRANSIT', 'IN TRANSIT', 'GOODS IN TRANSIT');
GO


------------------------ STOCK TYPE -------------------
INSERT INTO CONFIG_TYPE(CONFIG_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ('STOCK_TYPE', 'STOCK TYPE', 'STOCK TYPE');
GO

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_TYPE'),'STOCK_TYPE_STOCKABLE', 'STOCKABLE', 'Physical products where a stock count/inventory is kept');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_TYPE'),'STOCK_TYPE_NON_STOCKABLE', 'NON-STOCKABLE', 'Physical products where a stock count/inventory is not kept, for examplewhere the product is of such a little valuethat the cost of keeping an inventory of the stock outweights the value of the stock');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_TYPE'),'STOCK_TYPE_INTANGIBLE', 'INTANGIBLE', 'non physical product where a stock count/inventory can not be kept such as a service, delivery charge etc.');
GO

  ------------------------ STOCK CATEGORY -------------------
INSERT INTO CONFIG_TYPE(CONFIG_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ('STOCK_CATEGORY', 'STOCK CATEGORY', 'STOCK CATEGORY');
GO

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_SALEABLE', 'SALEABLE', 'Stock that is available for sale');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_NON_SALEABLE', 'NON SALEABLE', 'Stock that is not available for sale e.g. Held');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_RESERVED', 'RESERVED', 'Stock that is not available for sale because it is reserved');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_LAYAWAY', 'LAYAWAY', 'Stock that is not available for sale because it is held for LAYAWAY transaction');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_IN_DISPATCH', 'IN DISPATCH', 'Stock that is not available for sale because it is about to be dispatched in a Stock Transfer transaction');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_IN_TRANSIT', 'IN TRANSIT', 'Stock that is not available for sale because it is being transfered to site - we can consider this one for projects');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CATEGORY'),'STOCK_CATEGORY_RETURN', 'RETURN', 'Stock that is not available for sale because it is being prepared for return to warehouse, returns location or supplier');
GO

  ------------------------ STOCK CONDITION -------------------
INSERT INTO CONFIG_TYPE(CONFIG_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ('STOCK_CONDITION', 'STOCK CONDITION', 'STOCK CONDITION');
GO

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CONDITION'),'STOCK_CONDITION_PRISTINE', 'PRISTINE', 'Stock that is perfect and can be sold');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CONDITION'),'STOCK_CONDITION_DAMAGED', 'DAMAGED', 'Stock that has been classified as damaged and can be written off, returned, repaired or sold(e.g. at a discount');
GO
INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='STOCK_CONDITION'),'STOCK_CONDITION_FAULTY', 'FAULTY', 'Stock that has been classified as faulty and can be written off, returned, repaired or sold(e.g. at a discount');
GO


------ ASSIGNE STOCK_LOCATION TO ORG_UNIT AND STORE

INSERT INTO STOCK_LOCATION(ORGU_ID, STORE_ID, STCK_LOCN_CODE, STCK_LOCN_NAME, STCK_LOCN_ADDRESS) VALUES ((SELECT ORGU_ID FROM ORG_UNIT WHERE ORGU_CODE='JOMON'),(SELECT STORE_ID FROM STORE WHERE STORE_CODE='JOMON_SYD'),'STOCK_SYD', 'SYDNEY MAIN STOCK', '32 SPENCER STREET, FIVE DOCK, NSW 2046')
GO

-- customer comment

alter table customer add 	[COMMENT] [varchar](1000) NULL
go

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION, COLOR) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='CUSTOMER_STATUS'),'CUSTOMER_STATUS_ON_HOLD', 'ON HOLD', 'ON HOLD','amber');
GO

INSERT INTO CONFIG_CATEGORY(CONFIG_TYPE_ID, CATEGORY_CODE, DISPLAY_NAME, DESCRIPTION, COLOR) VALUES ((SELECT CONFIG_TYPE_ID FROM CONFIG_TYPE WHERE CONFIG_CODE='CUSTOMER_STATUS'),'CUSTOMER_STATUS_IN_ACTIVE', 'IN-ACTIVE', 'IN-ACTIVE','yellow');
GO

-- not applied to the jomon

drop index TXHDIX02 on TXN_HEADER
go

alter table txn_header alter column TXHD_TXN_NR varchar(200)
go

alter table txn_header alter column TXHD_ORIG_TXN_NR varchar(200)
go

CREATE INDEX TXHDIX02 ON TXN_HEADER
(TXHD_TXN_NR)
go
