USE [RETAIL]
GO

CREATE TABLE [dbo].[CONFIG_TYPE](
	[CONFIG_TYPE_ID] [int] IDENTITY (1,1) NOT NULL,
	[CONFIG_CODE] [varchar](100) NOT NULL,
	[DISPLAY_NAME] [varchar](200) NOT NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[CATEGORY_ORDER] [int] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CONFIG_CATEGORY](
	[CATEGORY_ID] DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
	[CONFIG_TYPE_ID] [int] NOT NULL,
	[CATEGORY_CODE] [varchar](100) NULL,
	[DISPLAY_NAME] [varchar](200) NOT NULL,
	[CATEGORY_ORDER] [int] ,
	[DESCRIPTION] [varchar](500) NULL,
	[COLOR] [varchar](100) NULL
) ON [PRIMARY]


CREATE TABLE [dbo].[Customer](
	[CUSTOMER_ID] DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
	[Customer_Type] DECIMAL(31,0),
	[First_Name] [varchar](100) NULL,
	[Sur_Name] [varchar](100) NULL,
	[Middle_Name] [varchar](100) NULL,
	[Company_Name] [nchar](100) NULL,
	[Date_Of_Birth] [datetime] NULL,
	[Address] [varchar](500) NULL,
	[Address2] [varchar](500) NULL,
	[E_Mail] [varchar](100) NULL,
	[Mobile] [varchar](20) NULL,
	[Phone] [varchar](20) NULL,
	[Web_Site] [nchar](100) NULL,
	[Code] [varchar](100) NULL,
	[Title] [varchar](10) NULL,
	[Fax] [varchar](20) NULL,
	[Grade_Id] [int] NULL,
	[COMMENT] [varchar](1000) NULL,
  CREDIT_LIMIT DECIMAL(31,6) DEFAULT 0 NOT NULL,
  OWING DECIMAL(31,6) DEFAULT 0 NOT NULL,
  REMAIN_CREDIT DECIMAL(31,6) DEFAULT 0 NOT NULL,
  CREDIT_DURATION DECIMAL(31,0) DEFAULT 0 NOT NULL,
  CREDIT_START_DATE datetime,
  CREDIT_START_EOM BIT DEFAULT 0 NOT NULL,
  [CUSTOMER_STATUS] DECIMAL(31,0)

) ON [PRIMARY]

CREATE TABLE [dbo].[CUSTOMER_GRADE](
	[GRADE_ID] [int] IDENTITY (1,1) NOT NULL,
	[GRADE_CODE] [varchar](20) NULL,
	[GRADE_NAME] [varchar](200) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[RATE] DECIMAL(31,6) NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CONTACT](
	[CONTACT_ID] DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
	[Title] [varchar](10) NULL,
	[First_Name] [varchar](100) NULL,
	[Sur_Name] [varchar](100) NULL,
	[Middle_Name] [varchar](100) NULL,
	[COUNTRY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[POST_CODE] [varchar](20) NULL,
	[ADDRESS1] [varchar](200) NULL,
	[ADDRESS2] [varchar](200) NULL,
	[E_MAIL] [varchar](100) NULL,
	[MOBILE] [varchar](20) NULL,
	[PHONE] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[WEB_SITE] [nchar](100) NULL,
  CONTACT_TYPE DECIMAL(31,0)

) ON [PRIMARY]

CREATE TABLE CUSTOMER_CONTACT(
    CUST_CONTACT_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    CUSTOMER_ID DECIMAL(31,0)  NOT NULL,
    CONTACT_ID DECIMAL(31,0)  NOT NULL
) ON [PRIMARY]
go

CREATE TABLE CUSTOMER_ACCOUNT_DEBT(
    CAD_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    CUSTOMER_ID DECIMAL(31,0)  NOT NULL,
    TXHD_ID DECIMAL(31,0)  NOT NULL,
    TXHD_TXN_NR varchar(200),
    CAD_AMOUNT_DEBT DECIMAL(31,6) DEFAULT 0 NOT NULL,
    BALANCE DECIMAL(31,6) DEFAULT 0 NOT NULL,
    CAD_START_DATE datetime,
    CAD_DUE_DATE datetime,
    CAD_PAYMENT_DATE datetime,
    CAD_PAIED BIT DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE [dbo].[SUPPLIER](
	[SUPPLIER_ID] DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
	[SUPPLIER_CODE] [varchar](50) NOT NULL,
	[SUPPLIER_NAME] [varchar](100) NOT NULL,
	[SUPPLIER_TYPE_ID] DECIMAL(31,0) NULL,
	[SUPPLIER_STATUS_ID] DECIMAL(31,0) NULL,
	[CONTACT_ID] DECIMAL(31,0) NULL,
	[LEAD_TIME] [int] NULL,
	[STOCK_COVER] [int] NULL,
	[MIN_ORDER_VALUE] [decimal](19,4) NULL,
	[CREDIT_LIMIT] [decimal](19,4) NULL,
	[MAX_ADV_ORDER] [int] NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL,
	[LAST_MODIFIED_BY] DECIMAL(31,0) NULL,
	[CONTACT_FIRST_NAME] [varchar](100) NULL,
	[CONTACT_SUR_NAME] [varchar](100) NULL,
	[CONTACT_TITLE] [varchar](20) NULL,
	[CONTACT_KNOWN_AS] [varchar](100) NULL,
  ACC_EXPORTED BIT DEFAULT 0 NOT NULL
) ON [PRIMARY]

CREATE TABLE PROJECT(
    PROJECT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PROJECT_NAME VARCHAR(500) NOT NULL,
    PROJECT_CODE VARCHAR(100) NOT NULL,
    PROJECT_DESCRIPTION VARCHAR(1000) ,
    PROJECT_ADDRESS VARCHAR(1000) ,
    QUOTE_NO VARCHAR(100) ,
    REFERENCE_NO VARCHAR(100) ,
    DATE_REQUIRED datetime NULL,
    TOTAL_COST DECIMAL(31,6),
    TOTAL_PRICE DECIMAL(31,6),
    CLIENT_ID DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE BILL_OF_QUANTITY(
    BOQ_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PROJECT_ID DECIMAL(31,0) NOT NULL,
    REFERENCE_CODE VARCHAR(100),
    BOQ_NAME VARCHAR(100),
    ORDER_NO VARCHAR(100),
    NOTE VARCHAR(1000),
    DATE_CREATED datetime NULL,
    BOQ_STATUS DECIMAL(31,0) NOT NULL,
    BOQ_LAST_MODIFIED_DATE datetime,
    BOQ_LAST_MODIFIED_BY DECIMAL(31,0),
    BOQ_VALUE_GROSS DECIMAL(31,6) DEFAULT 0 NOT NULL,
    BOQ_VALUE_NETT DECIMAL(31,6),
    BOQ_TOTAL_QTY DECIMAL(31,4),
    BOQ_TOTAL_LINES DECIMAL(31,4),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE BOQ_DETAIL(
    BOQ_DETAIL_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    BOQ_ID DECIMAL(31,0) NOT NULL,
    SUPPLIER_ID DECIMAL(31,0) NOT NULL,
    PRIB_ID DECIMAL(31,0),
    UNOM_ID DECIMAL(31,0) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PROD_IS_NEW BIT DEFAULT 0 NOT NULL,
    QUANTITY DECIMAL(31,4) NOT NULL,
    QTY_ON_STOCK DECIMAL(31,4) DEFAULT 0 NOT NULL,
    QTY_PURCHASED DECIMAL(31,4) DEFAULT 0 NOT NULL,
    QTY_RECEIVED DECIMAL(31,4) DEFAULT 0 NOT NULL,
    QTY_BALANCE DECIMAL(31,4) DEFAULT 0 NOT NULL,
    COMMENT VARCHAR(1000),
    CHANGE_COMMENT VARCHAR(1000),
    COST DECIMAL(31,6) NOT NULL,
    ITEM_VALUE DECIMAL(31,6) NULL,
    MARGIN DECIMAL(31,6),
    SELL_PRICE DECIMAL(31,6),
    BQD_STATUS DECIMAL(31,0) ,
    BQD_CREATION_TYPE DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go


CREATE TABLE LEGAL_TENDER(
    LEGT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    LEGT_CODE VARCHAR(10) NOT NULL,
    LEGT_NAME VARCHAR(60) NOT NULL,
    LEGT_URL_IMAGE VARCHAR(2048),
    LEGT_URL_THUMB VARCHAR(2048),
    LEGT_FROM_DATE datetime,
    LEGT_TO_DATE datetime,
    LEGT_NO_DECS DECIMAL(31,0) NOT NULL,
    LEGT_MASK VARCHAR(2048),
    LEGT_IS_EURO BIT DEFAULT 0 NOT NULL,
    LEGT_EURO_MEMBER DECIMAL(31,0) DEFAULT 0 NOT NULL,
    LEGT_SYMBOL VARCHAR(6),
    LEGT_NUMERIC_CODE VARCHAR(10),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PRICE_BAND(
    PRIB_ACTIVE BIT DEFAULT 1 NOT NULL,
    PRIB_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PRIB_CODE VARCHAR(10) NOT NULL,
    PRIB_NAME VARCHAR(60) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    LEGT_ID DECIMAL(31,0) NOT NULL,
    PRIB_TAX_INCLUDED BIT DEFAULT 0 NOT NULL,
    VALC_ID_CATEGORY DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
)ON [PRIMARY]
go

CREATE TABLE COMPANY(
    COMP_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    COMP_IS_TRADING BIT,
    COMP_OPEN_DATE datetime,
    COMP_CLOSE_DATE datetime,
    COMP_CHQ_PAYEE VARCHAR(60),
    COMP_STK_AUTH_VAL DECIMAL(31,6),
    COMP_TRADE_CUTOFF datetime,
    COMP_PWRD_VALIDITY DECIMAL(31,0),
    COMP_LOGOFF_PERIOD DECIMAL(31,0) DEFAULT 0 NOT NULL,
    COMP_FORCECRDSWIPE BIT DEFAULT 0 NOT NULL,
    COMP_SECURE_LOGOFF BIT DEFAULT 0 NOT NULL,
    COMP_PWD_RETRY DECIMAL(31,0) DEFAULT 3 NOT NULL,
    COMP_REF_DUP_RCPT BIT,
    COMP_RECON_ATTEMPT DECIMAL(31,0),
    COMP_REFUND_DAYS DECIMAL(31,0),
    COMP_REFUND_START datetime,
    COMP_REFUND_EXPIRY datetime,
    COMP_REFUND_DAYSGR DECIMAL(31,0),
    COMP_REFUND_POLICY VARCHAR(255),
    COMP_DISC_TAX_RULE BIT DEFAULT 0 NOT NULL,
    COMP_CVOUCH_DAYS DECIMAL(31,0),
    COMP_CVOUCH_POLICY VARCHAR(2048),
    COMP_GRACE_LIMIT DECIMAL(31,0) DEFAULT 0 NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE ORG_TYPE(
    ORGT_TYPE_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    ORGT_TYPE_NAME VARCHAR(60) NOT NULL,
    ORGT_TYPE_CODE VARCHAR(20) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go


CREATE TABLE ORG_UNIT(
    ORGU_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_NAME VARCHAR(60) NOT NULL,
    ORGU_DESC VARCHAR(2048),
    ORGU_CODE VARCHAR(10) NOT NULL,
    ORGT_TYPE_ID DECIMAL(31,0) NOT NULL,
    ORGU_SHORT_NAME VARCHAR(15),
    PRIB_ID DECIMAL(31,0),
    WARH_ID DECIMAL(31,0),
    OUTL_ID DECIMAL(31,0),
    COMP_ID DECIMAL(31,0),
    ORGU_DEF_LEGT_ID DECIMAL(31,0),
    ORGU_CREATED datetime,
    ORGU_MODIFIED datetime,
    ORGU_NEXT_PO FLOAT,
    ORGU_AUDIT_LEVEL DECIMAL(31,0),
    ORGU_SOFTWARE VARCHAR(10),
    ORGU_VAT_REG_NO VARCHAR(100),
    AIRP_ID DECIMAL(31,0),
    PRIB_ID_COST DECIMAL(31,0),
    ORGU_WEEE_REG_NO VARCHAR(100),
    ORGU_DEF_LANG_ID DECIMAL(31,0),
    ORGU_TIME_ZONE VARCHAR(60),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE STORE (
    STORE_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    COMPANY_CODE VARCHAR(10),
    STORE_CODE VARCHAR(10) NOT NULL,
    STORE_NAME VARCHAR(30),
    STORE_STATUS DECIMAL(31,0)
)
GO
CREATE TABLE TXN_HEADER (
    TXHD_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    STORE_ID DECIMAL(31,0) NOT NULL,
    TXHD_TXN_NR varchar(200),
    TXHD_PO_NR varchar(200),
    TXHD_STATE DECIMAL(31,0),
    ORGU_ID_ORIGINAL DECIMAL(31,0),
    TXHD_ORIG_TXN_NR varchar(200),
    TXHD_TRADING_DATE datetime,
    TXHD_TXN_TYPE DECIMAL(31,0) NOT NULL,
    TXHD_OPERATOR DECIMAL(31,0),
    TXHD_VOIDED BIT NOT NULL DEFAULT 0,
    TXHD_VALUE_GROSS DECIMAL(31,6),
    TXHD_VALUE_NETT DECIMAL(31,6),
    TXHD_VALUE_DUE DECIMAL(31,6),
    TXHD_VALUE_CHANGE DECIMAL(31,6),
    TXHD_VAL_ROUNDING DECIMAL(31,6),
    TXHD_VALUE_TAXABLE DECIMAL(31,6),
    TXHD_VALUE_TAX DECIMAL(31,6),
    TXHD_RECEIPT_ID VARCHAR(50),
    CUSTOMER_ID DECIMAL(31,0),
    TXHD_VOID_TXN_NR NUMERIC(10,0),
    TXHD_TAX_EXEMPT BIT NOT NULL DEFAULT 0,
    TXHD_REFUND_EXPIRY datetime,
    TXHD_COLLECT_DATE datetime,
    TXHD_DLV_ADDRESS VARCHAR(500),
    TXHD_CONTACT_PERSON VARCHAR(500),
    TXHD_CONTACT_PHONE VARCHAR(50),
    TXHD_EMAIL_TO VARCHAR(100),
    TXHD_PRINTED BIT DEFAULT 0
)
GO
CREATE TABLE TXN_DETAIL (
    TXDE_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    STORE_ID DECIMAL(31,0) NOT NULL,
    TXHD_ID DECIMAL(31,0) NOT NULL,
    TXDE_PRICE_OVRIDEN BIT NOT NULL DEFAULT 0,
    TXDE_PROD_ID DECIMAL(31,0) NOT NULL,
    TXDE_UNOM_ID DECIMAL(31,0),
    TXDE_VALUE_LINE DECIMAL(31,6),
    TXDE_PROFIT_MARGIN DECIMAL(31,6),
    TXDE_VALUE_PROFIT DECIMAL(31,6), --TXDE_VALUE_PROFIT= TXDE_VALUE_LINE * TXDE_PROFIT_MARGIN(WHICH IS BASE CUSTOMER)
    TXDE_VALUE_GROSS DECIMAL(31,6), --TXDE_VALUE_GROSS = (TXDE_VALUE_LINE + TXDE_VALUE_PROFIT)
    TXDE_TAX DECIMAL(31,6),
    TXDE_VALUE_NET DECIMAL(31,6),   --TXDE_VALUE_NET = TXDE_TAX*TXDE_VALUE_GROSS + TXDE_VALUE_GROSS
    TXDE_QUANTITY_SOLD DECIMAL(31,4),
    TXDE_QTY_INVOICED DECIMAL(31,4),
    TXDE_QTY_REFUND DECIMAL(31,4),
    TXDE_QTY_TOTAL_REFUND DECIMAL(31,4),
    TXDE_QTY_TOTAL_INVOICED DECIMAL(31,4),
    TXDE_QTY_BALANCE DECIMAL(31,4),
    TXDE_PRICE_SOLD DECIMAL(31,6),  --TXDE_VALUE_NET * TXDE_QUANTITY_SOLD
    TXDE_LINE_REFUND BIT NOT NULL DEFAULT 0,
    TXDE_ITEM_VOID BIT NOT NULL DEFAULT 0,
    TXDE_SERIAL_NUMBER VARCHAR(50),
    TXDE_WAS_SPLIT_PCK BIT NOT NULL DEFAULT 0,
    TXDE_DETAIL_LEVEL DECIMAL(31,0),
    TXDE_PARENT_DETAIL DECIMAL(31,0),
    TXDE_DETAIL_TYPE DECIMAL(31,0) NOT NULL,
    TXDE_DISC_PRICE DECIMAL(31,6),
    TXDE_RETURN_ORGU_ID DECIMAL(31,0),
    TXDE_RETURN_STORE_ID DECIMAL(31,0)
)
GO
CREATE TABLE MEDIA_TYPE  (
   MEDT_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   MEDT_NAME VARCHAR(100) NOT NULL,
   MEDT_DESC VARCHAR(200),
   MEDT_CODE VARCHAR(50) NOT NULL,
   MEDT_OPEN_DRAWER BIT NOT NULL DEFAULT 0,
   MEDT_ALLOW_EXCH_IN BIT NOT NULL DEFAULT 0,
   MEDT_ALLOW_EXCHOUT BIT NOT NULL DEFAULT 0,
   MEDT_REFUNDABLE BIT NOT NULL DEFAULT 0,
   MEDT_SHOW_EX_RATE BIT NOT NULL DEFAULT 0,
   MEDT_ALLOW_PAYIN BIT NOT NULL DEFAULT 0,
   MEDT_ALLOW_PAYOUT BIT NOT NULL DEFAULT 0,
   LCOUNT DECIMAL(31,0) NOT NULL DEFAULT 0
)
go

CREATE TABLE PAYMENT_MEDIA  (
   PAYM_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   PAYM_NAME VARCHAR(100) NOT NULL,
   PAYM_CODE VARCHAR(50) NOT NULL,
   LEGT_ID DECIMAL(31,0),
   MEDT_ID DECIMAL(31,0) NOT NULL,
   PAYM_CLASS_NAME VARCHAR(100),
   PAYM_ALWAYS_EURO BIT NOT NULL DEFAULT 0,
   PAYM_DISPLAY_TEXT VARCHAR(100),
   PAYM_REC_DIFF_VAL BIT DEFAULT 1,
   MAX_CHANGE DECIMAL(31,6),
   MAX_TENDER DECIMAL(31,6),
   MIN_TENDER DECIMAL(31,6),
   MAX_ONLINE_CASHBACK DECIMAL(31,6),
   MAX_OFFLINE_CASHBACK DECIMAL(31,6),
   USE_IN_STAFF_DISCOUNT BIT DEFAULT 0,
   MIN_ACCEPTABLE DECIMAL(31,6),
   TENDER_AUTH_THRESHOLD DECIMAL(31,6),
   IS_REVERSABLE BIT DEFAULT 0,
   LCOUNT DECIMAL(31,0) NOT NULL DEFAULT 0
 )
go

CREATE TABLE TXN_MEDIA(
  TXMD_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
  ORGU_ID DECIMAL(31,0) NOT NULL,
  STORE_ID DECIMAL(31,0) NOT NULL,
  TXHD_ID DECIMAL(31,0) NOT NULL,
  MEDT_ID DECIMAL(31,0),
  PAYM_ID DECIMAL(31,0),
  TXMD_TYPE DECIMAL(31,0) NOT NULL,
  TXMD_AMOUNT_LOCAL DECIMAL(38,6),
  TXMD_AMNT_FOREIGN DECIMAL(38,6),
  TXMD_PAN VARCHAR(20),
  TXMD_START_DATE VARCHAR(6),
  TXMD_EXPIRY_DATE VARCHAR(6),
  TXMD_ISSUE_NR DECIMAL(5,0),
  TXMD_SERIAL_ID VARCHAR(100),
  TXMD_NR_TENDERED SMALLINT,
  TXMD_AUTH_CODE VARCHAR(30),
  TXMD_VOIDED BIT DEFAULT 0 NOT NULL,
  TXMD_ACCOUNT_ID VARCHAR(100),
  TXMD_SORT_CODE VARCHAR(60),
  TXMD_AC_NAME VARCHAR(60),
  TXMD_MNEMONIC VARCHAR(6),
  TXMD_VOID_CODE VARCHAR(10),
  TXMD_GTEE_LIMIT DECIMAL(38,6),
  DEVC_TERMINAL_ID VARCHAR(60),
  TXMD_MERCHANT_ID VARCHAR(30),
  TXMD_EFT_SEQ_NO DECIMAL(38),
  TXMD_AUTH_ONLINE DECIMAL(38),
  TXMD_CUST_VERIFY DECIMAL(38),
  TXMD_CARD_APP_NO VARCHAR(60),
  TXMD_APP_CRYPT VARCHAR(128),
  TXMD_APP_CRYPT_TYP DECIMAL(38),
  TXMD_CARD_APP_EFF VARCHAR(6),
  TXMD_CARD_APP_EXP VARCHAR(6),
  TXMD_APP_PAN_SEQ DECIMAL(38),
  TXMD_CARD_SRVC_CD VARCHAR(10),
  TXMD_TENDER_DATE DATETIME,
  TXMD_VOIDING_LINE BIT DEFAULT 0 NOT NULL,
  TXMD_PARENT_DET_NR SMALLINT,
   LCOUNT DECIMAL(31,0) NOT NULL DEFAULT 0
 )
GO

--product group type
CREATE TABLE PRGP_TYPE(
    PRGT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PRGT_CODE VARCHAR(10) NOT NULL,
    PRGT_NAME VARCHAR(60) NOT NULL,
    PRGT_TYPE_CONST DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

--product group structure
CREATE TABLE PRODGP_STRUCTURE(
    PSTR_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PSTR_NAME VARCHAR(60) NOT NULL,
    PSTR_DESC VARCHAR(2048),
    PSTR_DATE_FROM datetime ,
    PSTR_DATE_TO datetime ,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PSTR_IS_LIVE BIT DEFAULT 0 NOT NULL,
    PSTR_MAX_LEVELS DECIMAL(31,0),
    PSTR_CONSTANT DECIMAL(31,0),
    LOCN_ID DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go
-- define hierarchy of product group structure
CREATE TABLE PRODGP_STRUCTURE_DETAIL(
    PGSD_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PGSD_LEVEL_NAME VARCHAR(60) NOT NULL,
    PGSD_LEVEL_DESC VARCHAR(2048),
    PGSD_ID_PARENT DECIMAL(31,0),
    PGSD_LEVEL DECIMAL(31,0) NOT NULL,
    PGSD_MANDATORY BIT DEFAULT 1 NOT NULL,
    PSTR_ID DECIMAL(31,0) NOT NULL,
    PRGT_ID DECIMAL(31,0) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PRODUCT_GROUP(
    PRGP_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PRGP_CODE VARCHAR(60) NOT NULL,
    PRGT_ID DECIMAL(31,0) NOT NULL,
    PRGP_DESC VARCHAR(2048),
    PRGP_NAME VARCHAR(60) NOT NULL,
    PRGP_CREATED datetime,
    PRGP_MODIFIED datetime,
    PRGP_CAN_BE_MERCH BIT DEFAULT 0 NOT NULL,
    PRGP_MAIN_PRGP_ID DECIMAL(31,0),
    PRGP_TRADE_START datetime,
    PRGP_TRADE_END datetime,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go


CREATE TABLE PRODGP_STR_LINK(
    PGSL_ID DECIMAL(31,0)IDENTITY(1,1) NOT NULL,
    PGSL_CAN_BE_RANGED BIT DEFAULT 1 NOT NULL,
    PRGP_ID DECIMAL(31,0) NOT NULL,
    PSTR_ID DECIMAL(31,0) NOT NULL,
    PRGP_PARENT_ID DECIMAL(31,0),
    PRGP_CHILD_ID DECIMAL(31,0),
    PGSL_DISPLAY_SEQ DECIMAL(31,0),
    PGSD_ID DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE TAX_RULE_NAME(
    TXRN_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    TXRN_NAME VARCHAR(60) NOT NULL,
    TXRN_CODE VARCHAR(20) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE TAX_RULE(
    TXRL_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    TXRL_DATE_FROM datetime NULL,
    TXRL_DATE_TO datetime NULL,
    TXRL_APPLY_SEQ DECIMAL(31,0) NOT NULL,
    TXRL_CUM_TAX BIT DEFAULT 0 NULL,
    TXRL_UPPER_VAL DECIMAL(31,6),
    TXRN_ID DECIMAL(31,0) NOT NULL,
    TXRL_CODE VARCHAR(10) NOT NULL,
    TXRL_DESC VARCHAR(30),
    TXRL_CALC_MTHD DECIMAL(31,0) DEFAULT 1 NULL,
    TXRL_LEGAL_DESC VARCHAR(2048),
    TXRL_ROUNDING_MTHD DECIMAL(31,0) DEFAULT 1,
    TXRL_STEPPED BIT DEFAULT 0 NOT NULL,
    TXRL_ACC_CODE VARCHAR(60),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE TAX_LEG_VARIANCE(
    TXLV_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    TXRL_ID DECIMAL(31,0) NOT NULL,
    TXLV_RATE DECIMAL(31,6),
    TXLV_DATETIME_FROM datetime NULL,
    TXLV_DATETIME_TO datetime NULL,
    TXLV_CODE VARCHAR(10),
    TXLV_DESC VARCHAR(30),
    TXLV_AMOUNT DECIMAL(31,6),
    TXLV_IS_ACTIVE BIT DEFAULT 0,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE UNIT_OF_MEASURE(
    UNOM_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    UNOM_CODE VARCHAR(10) NOT NULL,
    UNOM_DESC VARCHAR(2048) NULL,
    UNOM_FACTOR DECIMAL(31,0) NULL,
    UNOM_CREATED datetime NULL,
    UNOM_MODIFIED datetime NULL,
    UNOM_CONSTANT DECIMAL(31,0),
    UNOM_ID_PARENT DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PRODUCT(
    PROD_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PROD_SKU VARCHAR(200) NOT NULL,
    REFERENCE VARCHAR(200) NULL,
    ORGU_ID_OWNING DECIMAL(31,0) NOT NULL,
    PROD_NAME VARCHAR(500) NOT NULL,
    CAT_ID_TYPE DECIMAL(31,0) NULL,
    PROD_DESC VARCHAR(2048),
    PROD_OWN_BRAND BIT DEFAULT 0 NOT NULL,
    PROD_URL VARCHAR(2048),
    PROD_CREATED datetime,
    PROD_MODIFIED datetime,
    PROD_RECEIPT_DESC VARCHAR(200),
    PROD_WARRANTY_TERM DECIMAL(31,0),
    PROD_BRAND VARCHAR(60),
    PROD_IMAGE_DESC VARCHAR(500),
    PROD_URL_THUMB VARCHAR(2048),
    PROD_CLASS VARCHAR(30),
    PROD_WARRANTY_TEXT VARCHAR(255),
    PROD_LOCATION VARCHAR(1000),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PROD_ORGU_LINK(
    PROU_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PROU_REFUNDABLE DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PROU_DISCOUNTABLE DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PROU_CAN_QTY_SALE BIT DEFAULT 1 NOT NULL,
    PROU_FORCE_QTY DECIMAL(31,0) DEFAULT 0 NOT NULL,
    CAT_ID_STATUS DECIMAL(31,0) NOT NULL,
    PROU_REFUND_DAYS DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PROD_PGRP_LINK(
    PPGL_ID DECIMAL(31,0)IDENTITY(1,1) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRGP_ID DECIMAL(31,0) NOT NULL,
    PPGL_DISPLAY_SEQ DECIMAL(31,0),
    PPGL_REL_CONST DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PPGL_PRIORITY DECIMAL(31,0) DEFAULT 0 NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE SUPP_ORGU_LINK(
    SOL_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    SUPP_ID DECIMAL(31,0) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    CAT_ID_STATUS DECIMAL(31,0),
    SOL_CRED_LIMIT DECIMAL(31,6),
    SOL_MIN_ORD_VAL DECIMAL(31,6),
    SOL_LEAD_TIME DECIMAL(31,0),
    SOL_ORDERING_CODE VARCHAR(10),
    SOL_MIN_PO_QTY DECIMAL(31,4),
    SOL_PAYMENT_DAYS DECIMAL(31,0),
    SOL_ACC_CODE VARCHAR(60),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE SUPP_PROD_PRICE(
    SPRC_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    SOL_ID DECIMAL(31,0) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    CATALOGUE_NO VARCHAR(60),
    PART_NO VARCHAR(60),
    UNOM_ID_CONTENT DECIMAL(31,0),
    UNOM_ID DECIMAL(31,0) NOT NULL,
    UNOM_QTY DECIMAL(31,4) NOT NULL,
    PRICE DECIMAL(31,6),  --AFTER TAX
    COST_BEFORE_TAX DECIMAL(31,6),  --COST BEFORE TAX
    BULK_PRICE DECIMAL(31,6), --AFTER TAX
    BULK_PRICE_BEFORE_TAX DECIMAL(31,6), --BEFORE TAX
    BULK_QTY DECIMAL(31,4),
    LEGT_ID DECIMAL(31,0),
    TXLV_ID DECIMAL(31,0),
    SPRC_MIN_ORD_QTY DECIMAL(31,4),
    SPRC_LEAD_TIME DECIMAL(31,0),
    SPRC_CREATED DATETIME NULL,
    SPRC_MODIFIED DATETIME NULL,
    SPRC_PREFER_BUY BIT DEFAULT 0 NOT NULL,
    SPRC_MIN_ORD_VAL DECIMAL(31,6),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PRODUCT_METRIC(
    PRDM_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRDM_DRY_WEIGHT DECIMAL(31,4),
    UNOM_ID_DRY_WEIGHT DECIMAL(31,0),
    PRDM_WEIGHT DECIMAL(31,4),
    UNOM_ID_WEIGHT DECIMAL(31,0),
    PRDM_VOLUME DECIMAL(31,4),
    UNOM_ID_VOLUME DECIMAL(31,0),
    PRDM_QUANTITY DECIMAL(31,4),
    PRDM_PER_UNIT DECIMAL(31,4),
    UNOM_ID_PER_UNIT DECIMAL(31,0),
    PRDM_CASE_SIZE DECIMAL(31,0),
    PRDM_NUM_LABELS DECIMAL(31,0),
    PRDM_BARCODE_LOCAL DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PRDM_LENGTH DECIMAL(31,4),
    UNOM_ID_LENGTH DECIMAL(31,0),
    PRDM_DIM_HEIGHT DECIMAL(31,4),
    PRDM_DIM_WIDTH DECIMAL(31,4),
    PRDM_DIM_LENGTH DECIMAL(31,4),
    UNOM_ID_DIM DECIMAL(31,0),
    PRDM_USAGE DECIMAL(31,4),
    UNOM_ID_USAGE DECIMAL(31,0),
    UNOM_ID_UNIT DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0
) ON [PRIMARY]
go

CREATE TABLE PRICE_CODE(
    PRCC_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PRCC_NAME VARCHAR(60) NOT NULL,
    PRCC_CODE VARCHAR(10) NOT NULL,
    PRCC_CREATED datetime NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PRICE(
    PRCE_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRIB_ID DECIMAL(31,0) NOT NULL,
    PRCC_ID DECIMAL(31,0) NOT NULL,
    MARGIN DECIMAL(31,6),
    PRCE_FROM_DATE datetime NULL,
    PRCE_TO_DATE datetime NULL,
    PRCE_PRICE DECIMAL(31,6) NOT NULL,
    PRCE_CREATED datetime NULL,
    PRCE_MODIFIED datetime NULL,
    PRCE_TAX_INCLUDED BIT DEFAULT 0 NOT NULL,
    UNOM_ID DECIMAL(31,0),
    UNOM_QTY DECIMAL(31,4) NOT NULL,
    PRCE_SET_CENTRAL BIT DEFAULT 1 NOT NULL,
    PRCE_REDUCED BIT DEFAULT 0 NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PROD_TYPE(
    PRTY_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    PRTY_NAME VARCHAR(60) NOT NULL,
    PRTY_CONST DECIMAL(31,0) NOT NULL,
    PRTY_PRODUCT_TYPE DECIMAL(31,0) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go


CREATE TABLE PROD_TO_PROD_LINK(
    PRTY_ID DECIMAL(31,0) NOT NULL,
    PROD_ID_FROM DECIMAL(31,0) NOT NULL,
    PROD_ID_TO DECIMAL(31,0) NOT NULL,
    PTPL_COMPONENT_QTY DECIMAL(31,4) DEFAULT 1,
    PTPL_KIT_ONLY BIT DEFAULT 0,
    PTPL_COMP_MERCH BIT DEFAULT 0 NOT NULL,
    PTPL_SEQUENCE_NO DECIMAL(31,0) NOT NULL,
    UNOM_ID DECIMAL(31,0) NOT NULL,
    PTPL_DESC VARCHAR(2048),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
) ON [PRIMARY]
go

CREATE TABLE PROU_TXRL_LINK(
    PROU_ID DECIMAL(31,0) NOT NULL,
    TXRL_ID DECIMAL(31,0) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0
) ON [PRIMARY]
go

CREATE TABLE PURCHASE_ORDER_HEADER (
    POH_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    POH_ORDER_NUMBER VARCHAR(100),
  	SUPPLIER_ID DECIMAL(31,0),
    POH_SUPP_REF VARCHAR(100),
    POH_SUPP_CONTACT VARCHAR(60),
    POH_CREATED_DATE datetime,
    POH_LAST_MODIFIED_DATE datetime,
    POH_LAST_MODIFIED_BY DECIMAL(31,0),
    POH_LAST_DELV_DATE datetime,
    POH_CANCELLED BIT DEFAULT 0,
    POH_APPROVED BIT DEFAULT 0,
    POH_DELV_NAME VARCHAR(60),
    POH_DELV_ADDRESS VARCHAR(500),
    POH_DELV_PHONE VARCHAR(100),
    POH_DELV_MOBILE VARCHAR(100),
    POH_DELV_DATE datetime,
    POH_EXP_TRANSMIT datetime,
    POH_EXP_DELIVERY datetime,
    POH_ACT_TRANSMIT datetime,
    POH_CONFIRM_DATE datetime,
    POH_VALUE_GROSS DECIMAL(31,6) DEFAULT 0 NOT NULL,
    POH_VALUE_NETT DECIMAL(31,6),
    POH_VALUE_TAX DECIMAL(31,6),
    POH_TOTAL_QTY DECIMAL(31,4),
    POH_TOTAL_LINES DECIMAL(31,4),
    POH_TYPE DECIMAL(31,0),
    POH_STATUS DECIMAL(31,0) NOT NULL,
    POH_COMMENT VARCHAR(1000),
    POH_CREATION_TYPE DECIMAL(31,0),
    POH_PREFIX VARCHAR(200),
    POH_DLV_ADDRESS VARCHAR(1000),
    POH_CONTACT_PERSON VARCHAR(200),
    POH_CONTACT_PHONE VARCHAR(50),
    POH_EMAIL_TO VARCHAR(100),
    POH_REVISION DECIMAL(31,0) default 0,
    POH_PRINTED BIT DEFAULT 0,
    COSTS_INCLUDE_TAX BIT DEFAULT 0,
    POH_PRJ_NAME VARCHAR(1000),
    POH_PRJ_CODE VARCHAR(500)
)
GO

CREATE TABLE PURCHASE_LINE(
    POL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    POH_ID DECIMAL(31,0) NOT NULL,
    POH_ORDER_NUMBER VARCHAR(100) NOT NULL,
    POL_LINE_NUMBER DECIMAL(31,0) NOT NULL,
    SPRC_ID DECIMAL(31,0),
    POL_PROD_ID DECIMAL(31,0),
    POL_SUPP_ID DECIMAL(31,0),
    POL_UNIT_COST DECIMAL(31,6),
    POL_PRICE DECIMAL(31,6), -- COST BEFORE TAX
    POL_SPECIAL_BUY BIT DEFAULT 0 NOT NULL,
    TXLV_ID DECIMAL(31,0), --TAX CODE
    POL_VALUE_TAX DECIMAL(31,6), -- TAX VALUE FOR THIS LINE : POL_QTY_ORDERED * (POL_PRICE * TAX_RATE)
    UNOM_ID DECIMAL(31,0), --CASE SIZE
    POL_QTY_ORDERED DECIMAL(31,4),
    POL_QTY_RESERVED DECIMAL(31,4),
    POL_QTY_CANCELLED DECIMAL(31,4),
    POL_QTY_RECEIVED DECIMAL(31,4),
    POL_QTY_INVOICED DECIMAL(31,4),
    POL_VALUE_ORDERED DECIMAL(31,6), -- TOTAL NET VALUE OF THIS LINE AFTER TAX :POL_QTY_ORDERED * (POL_PRICE + POL_PRICE * TAX_RATE)
    POL_VALUE_GROSS DECIMAL(31,6), -- TOTAL GROSS VALUE OF THIS LINE BEFORE TAX :POL_QTY_ORDERED * (POL_PRICE )
    POL_VALUE_TAX DECIMAL(31,6),
    POL_VALUE_RECEIVED DECIMAL(31,6),
    POL_VALUE_INVOICED DECIMAL(31,6),
    POL_FREE_TEXT VARCHAR(255),
    POL_MODIFIED datetime ,
    POL_DATE_RECEIVED datetime,
    POL_PRICE_CHECKED BIT DEFAULT 0 NOT NULL,
    POL_ID_PARENT_LINE DECIMAL(31,0),
    POL_QTY_COUNTED DECIMAL(31,4),
    POL_CONTENTS DECIMAL(31,4), --CASE CONTAINS HOW MANY PRODUCT
    UNOM_ID_CONTENTS DECIMAL(31,0), --PRODUCT SIZE
    POL_STATUS DECIMAL(31,0),
    POL_CREATION_TYPE DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0
);

CREATE TABLE PO_BOQ_LINK(
    PBQL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    POH_ID DECIMAL(31,0) NOT NULL,
    POH_ORDER_NUMBER VARCHAR(100),
    POL_ID DECIMAL(31,0),
    BOQ_ID DECIMAL(31,0),
    BOQ_NAME VARCHAR(100),
    PROJECT_ID DECIMAL(31,0) NOT NULL,
    PROJECT_CODE VARCHAR(100),
    BOQ_DETAIL_ID DECIMAL(31,0),
    BOQ_QTY_TOTAL DECIMAL(31,4),
    PO_QTY_RECEIVED DECIMAL(31,4),
    BOQ_QTY_BALANCE DECIMAL(31,4),
    COMMENT VARCHAR(1000),
    BPQL_STATUS DECIMAL(31,0)
);


CREATE TABLE DELIVERY_NOTE_HEADER (
    DELN_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    DELN_NOTE_NUMBER VARCHAR(100),
    DELN_GRN VARCHAR(100),
    POH_ID DECIMAL(31,0),
    POH_ORDER_NUMBER VARCHAR(100),
  	SUPPLIER_ID DECIMAL(31,0),
    DELN_DELIVERY_DATE datetime,
    DELN_CREATED_DATE datetime,
    DELN_LAST_MODIFIED_DATE datetime,
    DELN_LAST_MODIFIED_BY DECIMAL(31,0),
    DELN_VALUE_GROSS DECIMAL(31,6),
    DELN_VALUE_NETT DECIMAL(31,6),
    POH_QTY_ORDERED DECIMAL(31,4),
    DELN_TOTAL_QTY DECIMAL(31,4),
    DELN_TOTAL_LINES DECIMAL(31,4),
    DELN_TYPE DECIMAL(31,0),
    DELN_STATUS DECIMAL(31,0) NOT NULL,
    DELN_COMMENT VARCHAR(4000),
    LEGT_ID DECIMAL(31,0),
    FREIGHT_TXRL_ID DECIMAL(31,0),
    FREIGHT_AMOUNT DECIMAL(31,6),
    FREIGHT_TAX DECIMAL(31,6),
    FREIGHT_TAX_CODE VARCHAR (50),
    DELN_SURCHARGE DECIMAL(31,6),
    DELN_TOTAL DECIMAL(31,6),
    DELN_TAX DECIMAL(31,6),
    ACC_EXPORTED BIT DEFAULT 0 NOT NULL,
    COSTS_INCLUDE_TAX BIT DEFAULT 0
)
GO

CREATE TABLE DELIVERY_NOTE_LINE(
    DLNL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    DELN_ID DECIMAL(31,0)NOT NULL,
    POL_ID DECIMAL(31,0), --PURCHASE ORDER LINE
    DELN_GRN VARCHAR(100),
    DLNL_LINE_NUMBER DECIMAL(31,0),
    SPRC_ID DECIMAL(31,0),
    DLNL_CASE_SIZE DECIMAL(31,0),  --UNIT OF MEASURE OF THE DELIVERY STATED ON THE DELIVERY NOTE: BOX ....
    DLNL_PRODUCT_SIZE DECIMAL(31,0),  --UNIT OF MEASURE OF THE PRODUCT EACH ...
    DLNL_UNIT_COST DECIMAL(31,6), -- UNITCOST STATED ON THE DELIVERY NOTE OF THE SUPPLIER
    DLNL_QTY DECIMAL(31,4),
    POL_QTY DECIMAL(31,4),
    RCVD_CASE_SIZE DECIMAL(31,0),  --UNIT OF MEASURE OF THE ACTUAL DELIVERY : BOX ....
    RCVD_PRODUCT_SIZE DECIMAL(31,0),  --UNIT OF MEASURE OF THE PRODUCT OF ACTUAL DELIVERY EACH ...
    RCVD_QTY DECIMAL(31,4), -- ACTUAL RECEIVED
    DLNL_VALUE_TAX DECIMAL(31,6),
    DLNL_VALUE_GROSS DECIMAL(31,6),
    TOTAL_COST DECIMAL(31,6),
    TXLV_ID DECIMAL(31,0), --TAX CODE
    DLNL_QTY_REJECTED DECIMAL(31,4),
    DLNL_STATUS DECIMAL(31,0),
    DLNL_DISCREPANCY BIT DEFAULT 0 NOT NULL,
    DLNL_COMMENT VARCHAR(4000)
);

CREATE TABLE PO_DEL_NOTE_LINK(
    PODLVL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    POH_ID DECIMAL(31,0) NOT NULL,
    POH_ORDER_NUMBER VARCHAR(100),
    DELN_ID DECIMAL(31,0),
    DELN_NOTE_NUMBER VARCHAR(100),
    DELN_GRN VARCHAR(100),
    DELN_DELIVERY_DATE datetime
);


CREATE TABLE APP_USER(
    USR_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    USR_NAME VARCHAR(100) NOT NULL,
    USR_PASS VARCHAR(100) NULL,
    USR_FIRST_NAME VARCHAR(200) NULL,
    USR_SUR_NAME VARCHAR(200) NULL,
    USR_ACTIVE BIT DEFAULT 1 NOT NULL,
    USR_DELETED BIT DEFAULT 0 NOT NULL,
    USR_LOGED_ON BIT DEFAULT 0 NOT NULL
);

CREATE TABLE APP_ROLE(
    ROLE_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ROLE_CODE VARCHAR(100) NULL,
    ROLE_NAME VARCHAR(500) NOT NULL,
    ROLE_DELETED BIT DEFAULT 0 NOT NULL,
    ROLE_DESC VARCHAR(500) NULL
);

CREATE TABLE APP_USER_ROLE(
    OP_ROLE_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    USR_ID DECIMAL(31,0) NOT NULL,
    ROLE_ID DECIMAL(31,0)NOT NULL
);

CREATE TABLE ACCESS_POINT(
    ACPT_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ACPT_NAME VARCHAR(200) NOT NULL,
    ACPT_TOKEN VARCHAR(100) NOT NULL,
    ACPT_HELP_URL VARCHAR(1000) NULL,
    ACPT_DESC VARCHAR(1000) NULL
);

CREATE TABLE USER_ACCESS(
    USR_ACS_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    USR_ID DECIMAL(31,0) NOT NULL,
    ACPT_ID DECIMAL(31,0)NOT NULL
);

CREATE TABLE ROLE_ACCESS(
    ROLE_ACS_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ROLE_ID DECIMAL(31,0) NOT NULL,
    ACPT_ID DECIMAL(31,0)NOT NULL
);

--PHYSICAL LOCATION OF STOCK.
CREATE TABLE STOCK_LOCATION(
    STCK_LOCN_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    STCK_LOCN_CODE VARCHAR(100) NULL,
    STCK_LOCN_NAME VARCHAR(100) NULL,
    STCK_LOCN_ADDRESS VARCHAR(500) NULL,
    ORGU_ID DECIMAL(31,0),
    STORE_ID DECIMAL(31,0)
);

CREATE TABLE STOCK(
    STCK_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    SUPPLIER_ID DECIMAL(31,0) NULL,
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRGP_ID DECIMAL(31,0),
    SELC_ID DECIMAL(31,0),
    ORGU_ID_LOCATION DECIMAL(31,0) NOT NULL,
    STCK_QTY DECIMAL(31,4) NOT NULL,
    UNOM_ID DECIMAL(31,0),
    STCK_COND DECIMAL(31,0) NOT NULL,
    STCK_CAT DECIMAL(31,0) NOT NULL,
    STCK_LOCN_ID DECIMAL(31,0),
    ORGU_ID_RESPBILITY DECIMAL(31,0),
    STCK_VALUE DECIMAL(31,6),
    STCK_LAST_VERIFIED datetime,
    LEGT_ID DECIMAL(31,0)
);

CREATE TABLE STOCK_EVENT(
    STCK_EVNT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    STCK_ID DECIMAL(31,0) NOT NULL,
    ORGU_ID DECIMAL(31,0),
    STORE_ID DECIMAL(31,0),
    USR_ID DECIMAL(31,0),
    SUPPLIER_ID DECIMAL(31,0) NULL,
    UNOM_ID DECIMAL(31,0),
    PROD_ID DECIMAL(31,0) NOT NULL,
    PRGP_ID DECIMAL(31,0),
    SELC_ID DECIMAL(31,0),
    STCK_EVNT_DATE datetime,
    TXN_DATE datetime,
    TXN_TYPE DECIMAL(31,0),
    TXN_HEADER DECIMAL(31,0),
    TXN_LINE DECIMAL(31,0),
    TXN_NUMBER VARCHAR(100),
    STCK_LOCN_ID DECIMAL(31,0),
    STCK_QTY DECIMAL(31,4) NOT NULL,
    SELL_PRICE DECIMAL(31,6),
    COST_PRICE DECIMAL(31,6),
    STCK_COND DECIMAL(31,0),
    STCK_CAT DECIMAL(31,0)
);

CREATE TABLE INVOICE (
    TXIV_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    TXHD_ID DECIMAL(31,0),
    ORGU_ID DECIMAL(31,0) NOT NULL,
    STORE_ID DECIMAL(31,0) NOT NULL,
    TXIV_TXN_NR varchar(200),
    TXIV_PO_NR varchar(200),
    TXHD_TXN_NR varchar(200),
    TXIV_TRADING_DATE datetime,
    TXIV_OPERATOR DECIMAL(31,0),
    TXIV_VALUE_GROSS DECIMAL(31,6),
    TXIV_VALUE_NETT DECIMAL(31,6),
    TXIV_VALUE_DUE DECIMAL(31,6),
    TXIV_VALUE_CHANGE DECIMAL(31,6),
    TXIV_VAL_ROUNDING DECIMAL(31,6),
    TXIV_VALUE_TAXABLE DECIMAL(31,6),
    TXIV_VALUE_TAX DECIMAL(31,6),
    TXIV_RECEIPT_ID VARCHAR(50),
    CUSTOMER_ID DECIMAL(31,0),
    TXIV_REFUND_EXPIRY datetime,
    TXIV_COLLECT_DATE datetime,
    TXIV_DLV_ADDRESS varchar(2000),
    TXIV_TXN_TYPE DECIMAL(31,0),
    TXIV_CONTACT_PERSON VARCHAR(500),
    TXIV_CONTACT_PHONE VARCHAR(50),
    TXIV_EMAIL_TO VARCHAR(100),
    TXIV_PRINTED BIT DEFAULT 0,
    TXIV_FULLY_REFUNDED BIT DEFAULT 0
)
GO

CREATE TABLE INVOICE_DETAIL (
    TXID_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    TXIV_ID DECIMAL(31,0),
    TXDE_ID DECIMAL(31,0),
    ORGU_ID DECIMAL(31,0) NOT NULL,
    STORE_ID DECIMAL(31,0) NOT NULL,
    TXID_QTY_INVOICED DECIMAL(31,4),
    TXID_QTY_REFUND DECIMAL(31,4),
    TXID_PRICE_SOLD DECIMAL(31,6),
    TXID_SURCHARGE DECIMAL(31,6) DEFAULT 0.00,
    TXID_LINE_TYPE DECIMAL(31,0)
)
GO

CREATE TABLE INVOICE_MEDIA (
    TXIM_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    TXIV_ID DECIMAL(31,0),
    TXMD_ID DECIMAL(31,0),
    ORGU_ID DECIMAL(31,0) NOT NULL,
    STORE_ID DECIMAL(31,0) NOT NULL,
    TXIM_LINE_TYPE DECIMAL(31,0)
)
GO

--CUSTOMER ACCOUNT DEBT PAYMENT
CREATE TABLE TXN_ACC_PAYMENT (
    TAP_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    TXHD_ID DECIMAL(31,0),
    CAD_ID DECIMAL(31,0),
    ORGU_ID DECIMAL(31,0) ,
    STORE_ID DECIMAL(31,0),
    TAP_PAYMENT_DATE datetime,
    TAP_AMOUNT_PAID DECIMAL(31,6)
)
GO


--CASH FLOW MANAGEMENT
CREATE TABLE CASH_SESSION  (
   CSSN_SESSION_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   TILL_SHORT_DESC VARCHAR(200),
   CSSN_OPERATOR DECIMAL(31,0),
   CSSN_TRADING_DATE datetime,
   CSSN_STATUS DECIMAL(31,0) NOT NULL,
   CSSN_START_DATE datetime,
   CSSN_IMBALANCE_RSN VARCHAR(500),
   CSSN_TXN_NR VARCHAR(100),
   CSSN_FORCED BIT DEFAULT 0 NOT NULL,
   CSSN_IS_OP_ACC BIT DEFAULT 1 NOT NULL,
   CSSN_SAP_CTRL_NR VARCHAR(100),
   CSSN_EXP_END_DATE datetime,
   CSSN_ACT_END_DATE datetime,
   CSSN_RECOCILE_DATE datetime,
   CSSN_METHOD_OPEN DECIMAL(31,0),
   CSSN_METHOD_CLOSE DECIMAL(31,0),
   CSSN_CYCLE_PERIOD DECIMAL(31,0),
   CSSN_CURRENT_CASH DECIMAL(31,6),
   CSSN_TOTAL_FLOAT DECIMAL(31,6) NOT NULL DEFAULT 0,
   CSSN_TOTAL_PICKUP DECIMAL(31,6) NOT NULL DEFAULT 0,
   ACC_EXPORTED BIT DEFAULT 0 NOT NULL
   )
go

CREATE TABLE SESSION_EVENT  (
   SEEV_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   SEEV_EVENT_TYPE DECIMAL(31,0) NOT NULL,
   SEEV_EVENT_DATE datetime,
   SEEV_OPERATOR DECIMAL(31,0),
   SEEV_REFERENCE VARCHAR(500),
   SEEV_COMMENT VARCHAR(500),
   SEEV_REASON VARCHAR(500),
   SEEV_COLLECT_DATE datetime,
   SEEV_COLLECT_REF VARCHAR(500),
   SEEV_PICKUP_NR VARCHAR(500),
   SEEV_PAY_IN_SLIP VARCHAR(500)
   )
go

CREATE TABLE SESSION_TOTAL  (
   SETL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   MEDT_ID DECIMAL(31,0),
   PAYM_ID DECIMAL(31,0),
   MEDIA_TOTAL_COUNT DECIMAL(31,4),
   MEDIA_TOTAL_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0
   )
go


CREATE TABLE SESSION_MEDIA  (
   SEME_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   SEEV_ID DECIMAL(31,0) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   MEDT_ID DECIMAL(31,0),
   PAYM_ID DECIMAL(31,0),
   SEME_MEDIA_COUNT DECIMAL(31,4),
   SEME_MEDIA_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0
   )
go

--DETAIL FOR SOME SESSION EVENT LIKE RECONCILIATION.
CREATE TABLE SESSION_EVENT_DETAIL  (
   SEDE_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   SEEV_ID DECIMAL(31,0),
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   MEDT_ID DECIMAL(31,0),
   PAYM_ID DECIMAL(31,0),
   MEDIA_COUNT_ACTUAL DECIMAL(31,4),
   MEDIA_COUNT_EXPECTED DECIMAL(31,4),
   MEDIA_COUNT_DIFF DECIMAL(31,4),
   MEDIA_VALUE_ACTUAL DECIMAL(38,6) NOT NULL DEFAULT 0,
   MEDIA_VALUE_EXPECTED DECIMAL(38,6) NOT NULL DEFAULT 0,
   MEDIA_VALUE_DIFF DECIMAL(38,6) NOT NULL DEFAULT 0,
   SEDE_COMMENT VARCHAR(500)
   )
go


CREATE TABLE TXN_SESSION_LINK  (
   TSL_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   TXN_ID DECIMAL(31,0),
   TXN_TYPE DECIMAL(31,0),
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   TILL_SHORT_DESC VARCHAR(100),
   TXHD_TXN_NR VARCHAR(100),
   TSL_DATE_CREATED datetime
   )
go


CREATE TABLE TOTAL_SALE_OPERATOR  (
   TOOP_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   TOOP_OPERATOR DECIMAL(31,0),
   TOOP_TXN_TYPE DECIMAL(31,0),
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   TOOP_TRADING_DATE datetime,
   TOOP_SALE_QTY DECIMAL(31,4) NOT NULL DEFAULT 0, --TOTAL SALE ITEMS
   TOOP_ITEMS_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0, -- ITEM COST
   TOOP_PROFIT_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0, -- PROFIT GAINED ON SELLING ITEMS
   TOOP_TAXED_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0, -- VALUE ELIGIBLE FOR TAX
   TOOP_TAX_PAID DECIMAL(38,6) NOT NULL DEFAULT 0, -- AMOUNT PAID FOR TAX
   TOOP_SALE_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0, -- ITEM VALUE + PROFIT VALUE + TAXED PAID
   TOOP_REFUND_QTY DECIMAL(31,4) NOT NULL DEFAULT 0, -- TOTAL REFUND ITEMS
   TOOP_REFUND_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0,
   TOOP_DISCOUNT_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0, -- DISCOUNT APPLIED OT ITEMS
   TOOP_VOID_QTY DECIMAL(31,4) NOT NULL DEFAULT 0, -- TOTAL REFUND ITEMS
   TOOP_VOID_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0
   )
go

CREATE TABLE TOTAL_TAX_GROUP  (
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   TOTG_TXRL_ID DECIMAL(31,0) NOT NULL,
   TOTG_TRADING_DATE datetime NOT NULL,
   TOTG_TXGP_CODE VARCHAR(10) NOT NULL,
   TOTG_TAXED_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0,
   TOTG_TAX DECIMAL(38,6) NOT NULL DEFAULT 0,
   TOTG_TOT_SALES_QTY DECIMAL(31,4)
   )
go


CREATE TABLE TOTAL_MEDIA_OPERATOR  (
   TOMO_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   TOMO_OPERATOR DECIMAL(31,0) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   STORE_ID DECIMAL(31,0) NOT NULL,
   TOMO_TRADING_DATE datetime NOT NULL,
   MEDT_ID DECIMAL(31,0),
   PAYM_ID DECIMAL(31,0),
   TOMO_SALE_QTY DECIMAL(31,4) NOT NULL DEFAULT 0,
   TOMO_SALE_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0,
   TOMO_REFUND_QTY DECIMAL(31,4) NOT NULL DEFAULT 0,
   TOMO_REFUMND_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0,
   TOMO_CASHBACK_QTY DECIMAL(31,4) NOT NULL DEFAULT 0,
   TOMO_CASHBACK_VALUE DECIMAL(38,6) NOT NULL DEFAULT 0
   )
go

CREATE TABLE ACCOUNT  (
   ACC_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   ACC_TYPE DECIMAL(31,0) NOT NULL,
   ACC_CODE VARCHAR(50),
   ACC_NAME VARCHAR(100),
   ACC_DESC VARCHAR(500)
   )
go

CREATE TABLE JOURNAL_ENTRY  (
   JRN_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   CSSN_SESSION_ID DECIMAL(31,0) NOT NULL,
   SRC_TXN_TYPE DECIMAL(31,0),
   SRC_TXN_ID DECIMAL(31,0),
   APP_USER_ID DECIMAL(31,0) NOT NULL,
   ACC_ID DECIMAL(31,0) NOT NULL,
   JRN_ACC_CODE VARCHAR(50),
   JRN_ACC_DESC VARCHAR(100),
   JRN_DEBIT DECIMAL(38,6),
   JRN_CREDIT DECIMAL(38,6),
   JRN_DATE datetime,
   JRN_TAX_CODE VARCHAR(100),
   JRN_ACTUAL BIT DEFAULT 1 -- NON ACTUAL ENTRIES LIKE BANK ACCOUNTS(0) DOSE NOT SHOW ON JOURNAL BECAUSE IT GET REPLACED AT RECONCILIATION BY ACTUAL VALUE
   )
go

CREATE TABLE JOURNAL_SUPPORT  (
     JRN_ID DECIMAL(31,0) NOT NULL,
     TXMD_ID DECIMAL(31,0) NOT NULL
   )
go


CREATE TABLE JOURNAL_RULE  (
   JRNR_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
   ORGU_ID DECIMAL(31,0) NOT NULL,
   TXN_TYPE DECIMAL(31,0) NOT NULL,
   JRNR_ACTION DECIMAL(31,0) NOT NULL,
   ACC_ID DECIMAL(31,0) NOT NULL,
   JRNR_ACC_CODE VARCHAR(50),
   JRNR_ACC_DESC VARCHAR(500),
   JRNR_DEBIT BIT DEFAULT 0,
   JRNR_CREDIT BIT DEFAULT 0,
   JRNR_ACTUAL BIT DEFAULT 1 -- NON ACTUAL ENTRIES LIKE BANK ACCOUNTS(0) DOSE NOT SHOW ON JOURNAL BECAUSE IT GET REPLACED AT RECONCILIATION BY ACTUAL VALUE
   )
go


CREATE TABLE ACCOUNTING_EXPORT  (
     ACC_EXP_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
     ORGU_ID DECIMAL(31,0) NOT NULL,
     STORE_ID DECIMAL(31,0) NOT NULL,
     APP_USER_ID DECIMAL(31,0) NOT NULL,
     EXPORT_SUPPLIERS BIT DEFAULT 0,
     EXPORT_DELIVERY_NOTES BIT DEFAULT 0,
     EXPORT_JOURNAL_ENTRIES BIT DEFAULT 0,
     EXPORTED_CONTENT NVARCHAR(MAX),
     EXPORT_TIME datetime
   )
go

CREATE TABLE ACC_EXPORT_SUPP_LINK  (
     ACC_EXP_ID DECIMAL(31,0) NOT NULL,
     SUPPLIER_ID DECIMAL(31,0) NOT NULL
   )
go

CREATE TABLE ACC_EXPORT_DELN_LINK  (
     ACC_EXP_ID DECIMAL(31,0) NOT NULL,
     DELN_ID DECIMAL(31,0) NOT NULL
   )
go

CREATE TABLE ACC_EXPORT_SESSION_LINK  (
     ACC_EXP_ID DECIMAL(31,0) NOT NULL,
     CSSN_SESSION_ID DECIMAL(31,0) NOT NULL
   )
go

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
go

ALTER TABLE CUSTOMER_GRADE ADD CONSTRAINT GRADE_PK PRIMARY KEY(GRADE_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY(SUPPLIER_ID)
go

ALTER TABLE CONFIG_TYPE ADD CONSTRAINT CONFIG_TYPE_PK PRIMARY KEY(CONFIG_TYPE_ID)
go

ALTER TABLE CONFIG_CATEGORY ADD CONSTRAINT CATEGORY_PK PRIMARY KEY(CATEGORY_ID)
go

ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_PK PRIMARY KEY(CONTACT_ID)
go

ALTER TABLE LEGAL_TENDER ADD CONSTRAINT LEGAL_TENDER_PK PRIMARY KEY(LEGT_ID)
go

ALTER TABLE PRICE_BAND ADD CONSTRAINT PRIB_PK PRIMARY KEY (PRIB_ID)
go

ALTER TABLE COMPANY ADD CONSTRAINT COMPANY_PK PRIMARY KEY(COMP_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_PK PRIMARY KEY(ORGU_ID)
go

ALTER TABLE PRGP_TYPE ADD CONSTRAINT PRGP_TYPE_PK PRIMARY KEY(PRGT_ID)
go

ALTER TABLE PRODGP_STRUCTURE ADD CONSTRAINT PRODGP_STRUCTURE_PK PRIMARY KEY(PSTR_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PK PRIMARY KEY(PGSD_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_PK PRIMARY KEY(PRGP_ID)
go

ALTER TABLE ORG_TYPE ADD CONSTRAINT ORG_TYPE_PK PRIMARY KEY(ORGT_TYPE_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PK PRIMARY KEY(PGSL_ID)
go

ALTER TABLE TAX_RULE_NAME ADD CONSTRAINT TXRN_PK PRIMARY KEY (TXRN_ID)
go

ALTER TABLE TAX_RULE ADD CONSTRAINT TXRL_PK PRIMARY KEY (TXRL_ID)
go

ALTER TABLE TAX_LEG_VARIANCE ADD CONSTRAINT TXLV_PK PRIMARY KEY (TXLV_ID)
go

ALTER TABLE UNIT_OF_MEASURE ADD CONSTRAINT UNOM_PK PRIMARY KEY (UNOM_ID)
go

ALTER TABLE PRODUCT ADD CONSTRAINT PROD_PK PRIMARY KEY (PROD_ID)
go

ALTER TABLE PROD_ORGU_LINK ADD CONSTRAINT PROU_PK PRIMARY KEY (PROU_ID)
go

ALTER TABLE PROD_PGRP_LINK
 ADD  CONSTRAINT PPGL_PK PRIMARY KEY(PPGL_ID);

ALTER TABLE SUPP_ORGU_LINK ADD CONSTRAINT SOL_PK PRIMARY KEY (SOL_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_PK PRIMARY KEY (SPRC_ID)
go


ALTER TABLE PRODUCT_METRIC ADD CONSTRAINT PRDM_PK PRIMARY KEY (PRDM_ID)
go

ALTER TABLE PRICE_CODE ADD CONSTRAINT PRCC_PK PRIMARY KEY (PRCC_ID)
go

ALTER TABLE PRICE ADD CONSTRAINT PRCE_PK PRIMARY KEY (PRCE_ID)
go

ALTER TABLE PROD_TYPE ADD CONSTRAINT PRLT_PK PRIMARY KEY (PRTY_ID)
go

ALTER TABLE PROU_TXRL_LINK
 ADD  CONSTRAINT POTL_PK PRIMARY KEY(PROU_ID,TXRL_ID);
GO


ALTER TABLE PROJECT
 ADD  CONSTRAINT PROJECT_PK PRIMARY KEY(PROJECT_ID);
GO

ALTER TABLE BILL_OF_QUANTITY
 ADD  CONSTRAINT BILL_OF_QUANTITY_PK PRIMARY KEY(BOQ_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_PK PRIMARY KEY(BOQ_DETAIL_ID);
GO

ALTER TABLE STORE
 ADD  CONSTRAINT STORE_PK PRIMARY KEY(STORE_ID);
GO

ALTER TABLE TXN_HEADER
 ADD  CONSTRAINT TXN_HEADER_PK PRIMARY KEY(TXHD_ID);
GO

ALTER TABLE TXN_DETAIL
 ADD  CONSTRAINT TXN_DETAIL_PK PRIMARY KEY(TXDE_ID);
GO


ALTER TABLE MEDIA_TYPE
 ADD  CONSTRAINT MEDIA_TYPE_PK PRIMARY KEY(MEDT_ID);
GO

ALTER TABLE PAYMENT_MEDIA
 ADD  CONSTRAINT PAYMENT_MEDIA_PK PRIMARY KEY(PAYM_ID);
GO

ALTER TABLE TXN_MEDIA
 ADD  CONSTRAINT TXN_MEDIA_PK PRIMARY KEY(TXMD_ID);
GO

ALTER TABLE PURCHASE_ORDER_HEADER
 ADD  CONSTRAINT POH_PK PRIMARY KEY(POH_ID);
GO

ALTER TABLE PURCHASE_LINE
 ADD  CONSTRAINT PL_PK PRIMARY KEY(POL_ID);
GO

ALTER TABLE PO_BOQ_LINK
 ADD  CONSTRAINT POBOQL_PK PRIMARY KEY(PBQL_ID);
GO


ALTER TABLE DELIVERY_NOTE_HEADER
 ADD  CONSTRAINT DELIVERY_NOTE_HEADER_PK PRIMARY KEY(DELN_ID);
GO

ALTER TABLE DELIVERY_NOTE_LINE
 ADD  CONSTRAINT DELIVERY_NOTE_LINE_PK PRIMARY KEY(DLNL_ID);
GO

ALTER TABLE PO_DEL_NOTE_LINK
 ADD  CONSTRAINT PO_DEL_NOTE_LINK_PK PRIMARY KEY(PODLVL_ID);
GO


ALTER TABLE CUSTOMER_CONTACT
 ADD  CONSTRAINT CUSTOMER_CONTACT_PK PRIMARY KEY(CUST_CONTACT_ID);
GO

ALTER TABLE APP_USER
 ADD  CONSTRAINT APP_USER_PK PRIMARY KEY(USR_ID);
GO

ALTER TABLE APP_ROLE
 ADD  CONSTRAINT APP_ROLE_PK PRIMARY KEY(ROLE_ID);
GO

ALTER TABLE APP_USER_ROLE
 ADD  CONSTRAINT APP_USER_ROLE_PK PRIMARY KEY(OP_ROLE_ID);
GO


ALTER TABLE ACCESS_POINT
 ADD  CONSTRAINT ACCESS_POINT_PK PRIMARY KEY(ACPT_ID);
GO

ALTER TABLE USER_ACCESS
 ADD  CONSTRAINT USER_ACCESS_PK PRIMARY KEY(USR_ACS_ID);
GO

ALTER TABLE ROLE_ACCESS
 ADD  CONSTRAINT ROLE_ACCESS_PK PRIMARY KEY(ROLE_ACS_ID);
GO

ALTER TABLE STOCK_LOCATION
 ADD  CONSTRAINT STOCK_LOCATION_PK PRIMARY KEY(STCK_LOCN_ID);
GO

ALTER TABLE STOCK
 ADD  CONSTRAINT STOCK_PK PRIMARY KEY(STCK_ID);
GO

ALTER TABLE STOCK_EVENT
 ADD  CONSTRAINT STOCK_EVENT_PK PRIMARY KEY(STCK_EVNT_ID);
GO

ALTER TABLE INVOICE
 ADD  CONSTRAINT INVOICE_PK PRIMARY KEY(TXIV_ID);
GO

ALTER TABLE INVOICE_DETAIL
 ADD  CONSTRAINT INVOICE_DETAIL_PK PRIMARY KEY(TXID_ID);
GO

ALTER TABLE INVOICE_MEDIA
 ADD  CONSTRAINT INVOICE_MEDIA_PK PRIMARY KEY(TXIM_ID);
GO

ALTER TABLE CUSTOMER_ACCOUNT_DEBT
 ADD  CONSTRAINT CUSTOMER_ACCOUNT_DEBT_PK PRIMARY KEY(CAD_ID);
GO

ALTER TABLE TXN_ACC_PAYMENT
 ADD  CONSTRAINT TXN_ACC_PAYMENT_PK PRIMARY KEY(TAP_ID);
GO

ALTER TABLE CASH_SESSION
 ADD  CONSTRAINT CASH_SESSION_PK PRIMARY KEY(CSSN_SESSION_ID);
GO

ALTER TABLE SESSION_EVENT
 ADD  CONSTRAINT SESSION_EVENT_PK PRIMARY KEY(SEEV_ID);
GO

ALTER TABLE SESSION_MEDIA
 ADD  CONSTRAINT SESSION_MEDIA_PK PRIMARY KEY(SEME_ID);
GO

ALTER TABLE SESSION_EVENT_DETAIL
 ADD  CONSTRAINT SESSION_EVENT_DETAIL_PK PRIMARY KEY(SEDE_ID);
GO

ALTER TABLE SESSION_TOTAL
 ADD  CONSTRAINT SESSION_TOTAL_PK PRIMARY KEY(SETL_ID);
GO

ALTER TABLE TXN_SESSION_LINK
 ADD  CONSTRAINT TXN_SESSION_LINK_PK PRIMARY KEY(TSL_ID);
GO

ALTER TABLE TOTAL_SALE_OPERATOR
 ADD  CONSTRAINT TOTAL_SALE_OPERATOR_PK PRIMARY KEY(TOOP_ID);
GO

ALTER TABLE TOTAL_MEDIA_OPERATOR
 ADD  CONSTRAINT TOTAL_MEDIA_OPERATOR_PK PRIMARY KEY(TOMO_ID);
GO

ALTER TABLE ACCOUNT
 ADD  CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACC_ID);
GO


ALTER TABLE JOURNAL_ENTRY
 ADD  CONSTRAINT JOURNAL_ENTRY_PK PRIMARY KEY(JRN_ID);
GO

ALTER TABLE JOURNAL_RULE
 ADD  CONSTRAINT JOURNAL_RULE_PK PRIMARY KEY(JRNR_ID);
GO

ALTER TABLE ACCOUNTING_EXPORT
 ADD  CONSTRAINT ACCOUNTING_EXPORT_PK PRIMARY KEY(ACC_EXP_ID);
GO



ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_2GRADE_FK FOREIGN KEY (GRADE_ID) REFERENCES CUSTOMER_GRADE(GRADE_ID)
go

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_FK2 FOREIGN KEY (Customer_Type) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_FK3 FOREIGN KEY (CUSTOMER_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE CONFIG_CATEGORY ADD CONSTRAINT CATEGORY_2TYPE_FK FOREIGN KEY (CONFIG_TYPE_ID) REFERENCES CONFIG_TYPE(CONFIG_TYPE_ID)
go



ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_TYEP_ID_2CATEGORY_FK FOREIGN KEY (SUPPLIER_TYPE_ID) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_STATUS_ID_2CATEGORY_FK FOREIGN KEY (SUPPLIER_STATUS_ID) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_CONTACT_ID_2CONTACT_FK FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID)
go


ALTER TABLE LEGAL_TENDER ADD CONSTRAINT LEGT_UK1 UNIQUE(LEGT_CODE)
go


ALTER TABLE PRICE_BAND ADD CONSTRAINT PRIB_UK1 UNIQUE(PRIB_CODE)
go

ALTER TABLE PRICE_BAND ADD CONSTRAINT PRIB_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRICE_BAND ADD CONSTRAINT PRIB_FK3 FOREIGN KEY (LEGT_ID) REFERENCES LEGAL_TENDER(LEGT_ID)
go


ALTER TABLE ORG_TYPE ADD CONSTRAINT ORGT_UK1 UNIQUE(ORGT_TYPE_NAME)
go



ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_ORGU_ID_2ORG_UNIT_FK FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_PRGT_ID_2PRGP_TYPE_FK FOREIGN KEY (PRGT_ID) REFERENCES PRGP_TYPE(PRGT_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRGP_FK4 FOREIGN KEY (PRGP_MAIN_PRGP_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRGP_UK1 UNIQUE(PRGP_CODE,
   ORGU_ID,
   PRGT_ID)
go


ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_COMP_ID_2COMPANY_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY(COMP_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_ORGT_TYPE_ID_2ORG_TYPE_FK FOREIGN KEY (ORGT_TYPE_ID) REFERENCES ORG_TYPE(ORGT_TYPE_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORGU_FK8 FOREIGN KEY (PRIB_ID_COST) REFERENCES PRICE_BAND(PRIB_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORGU_FK5 FOREIGN KEY (PRIB_ID) REFERENCES PRICE_BAND(PRIB_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORGU_FK2 FOREIGN KEY (ORGU_DEF_LEGT_ID) REFERENCES LEGAL_TENDER(LEGT_ID)
go

ALTER TABLE PRODGP_STRUCTURE ADD CONSTRAINT PRODGP_STRUCTURE_ORGU_ID_2ORG_UNIT_FK FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PSTR_ID_2PRODGP_STRUCTURE_FK FOREIGN KEY (PSTR_ID) REFERENCES PRODGP_STRUCTURE(PSTR_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PRGT_ID_2PRGP_TYPE_FK FOREIGN KEY (PRGT_ID) REFERENCES PRGP_TYPE(PRGT_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PSTR_ID_2PRODGP_STRUCTURE_FK FOREIGN KEY (PSTR_ID) REFERENCES PRODGP_STRUCTURE(PSTR_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_PARENT_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_PARENT_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_CHILD_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_CHILD_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PGSD_ID_2PRODGP_STRUCTURE_DETAIL_FK FOREIGN KEY (PGSD_ID) REFERENCES PRODGP_STRUCTURE_DETAIL(PGSD_ID)
go

ALTER TABLE TAX_RULE_NAME ADD CONSTRAINT TXRN_UK1 UNIQUE(TXRN_NAME)
go

ALTER TABLE TAX_RULE ADD CONSTRAINT TXRL_FK1 FOREIGN KEY (TXRN_ID) REFERENCES TAX_RULE_NAME(TXRN_ID)
go

ALTER TABLE TAX_LEG_VARIANCE ADD CONSTRAINT TXLV_FK1 FOREIGN KEY (TXRL_ID) REFERENCES TAX_RULE(TXRL_ID)
go

ALTER TABLE UNIT_OF_MEASURE ADD CONSTRAINT UNOM_UK1 UNIQUE(UNOM_CODE)
go

ALTER TABLE UNIT_OF_MEASURE ADD CONSTRAINT UNOM_FK1 FOREIGN KEY (UNOM_ID_PARENT) REFERENCES UNIT_OF_MEASURE(UNOM_ID)
go


ALTER TABLE PRODUCT ADD CONSTRAINT PROD_UK1 UNIQUE(PROD_SKU,
   ORGU_ID_OWNING)
go

ALTER TABLE PRODUCT ADD CONSTRAINT PROD_FK6 FOREIGN KEY (ORGU_ID_OWNING) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_FK1 FOREIGN KEY (CAT_ID_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go



ALTER TABLE PROD_ORGU_LINK ADD CONSTRAINT PROU_FK3 FOREIGN KEY (CAT_ID_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE PROD_ORGU_LINK ADD CONSTRAINT PROU_FK1 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE PROD_ORGU_LINK ADD CONSTRAINT PROU_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PROD_PGRP_LINK
 ADD  CONSTRAINT PPGL_FK2 FOREIGN KEY(PRGP_ID) REFERENCES PRODUCT_GROUP(PRGP_ID);

ALTER TABLE PROD_PGRP_LINK
 ADD  CONSTRAINT PPGL_FK1 FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID);

ALTER TABLE SUPP_ORGU_LINK ADD CONSTRAINT SOL_UK1 UNIQUE(SUPP_ID,
   ORGU_ID)
go

ALTER TABLE SUPP_ORGU_LINK ADD CONSTRAINT SOL_FK1 FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
go

ALTER TABLE SUPP_ORGU_LINK ADD CONSTRAINT SOL_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE SUPP_ORGU_LINK ADD CONSTRAINT SOL_FK3 FOREIGN KEY (CAT_ID_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go


ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_UK1 UNIQUE(SOL_ID,
   PROD_ID,
   UNOM_ID,
   UNOM_QTY)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK5 FOREIGN KEY (LEGT_ID) REFERENCES LEGAL_TENDER(LEGT_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK2 FOREIGN KEY (SOL_ID) REFERENCES SUPP_ORGU_LINK(SOL_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK3 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK1 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK4 FOREIGN KEY (UNOM_ID_CONTENT) REFERENCES UNIT_OF_MEASURE(UNOM_ID)
go

ALTER TABLE SUPP_PROD_PRICE ADD CONSTRAINT SPRC_FK6 FOREIGN KEY (TXLV_ID) REFERENCES TAX_LEG_VARIANCE(TXLV_ID)
go

ALTER TABLE PRODUCT_METRIC ADD CONSTRAINT PRDM_FK2 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE PRICE_CODE ADD CONSTRAINT PRCC_UK1 UNIQUE(PRCC_CODE)
go

ALTER TABLE PRICE ADD CONSTRAINT PRCE_FK2 FOREIGN KEY (PRCC_ID) REFERENCES PRICE_CODE(PRCC_ID)
go

ALTER TABLE PRICE ADD CONSTRAINT PRCE_FK3 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE PRICE ADD CONSTRAINT PRCE_FK1 FOREIGN KEY (PRIB_ID) REFERENCES PRICE_BAND(PRIB_ID)
go

ALTER TABLE PRICE ADD CONSTRAINT PRCE_FK4 FOREIGN KEY (UNOM_ID) REFERENCES unit_of_measure(UNOM_ID)
go

ALTER TABLE PROD_TO_PROD_LINK ADD CONSTRAINT PTPL_PK PRIMARY KEY (PROD_ID_FROM,
  PRTY_ID,
  PROD_ID_TO)
go

ALTER TABLE PROD_TO_PROD_LINK ADD CONSTRAINT PTPL_FK4 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID)
go

ALTER TABLE PROD_TO_PROD_LINK ADD CONSTRAINT PTPL_FK1 FOREIGN KEY (PROD_ID_TO) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE PROD_TO_PROD_LINK ADD CONSTRAINT PTPL_FK2 FOREIGN KEY (PROD_ID_FROM) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE PROD_TO_PROD_LINK ADD CONSTRAINT PTPL_FK3 FOREIGN KEY (PRTY_ID) REFERENCES PROD_TYPE(PRTY_ID)
go

ALTER TABLE PROU_TXRL_LINK
 ADD  CONSTRAINT POTL_FK1 FOREIGN KEY(PROU_ID) REFERENCES PROD_ORGU_LINK(PROU_ID);
GO

ALTER TABLE PROU_TXRL_LINK
 ADD  CONSTRAINT POTL_FK2 FOREIGN KEY(TXRL_ID) REFERENCES TAX_RULE(TXRL_ID);
GO

ALTER TABLE BILL_OF_QUANTITY
 ADD  CONSTRAINT BILL_OF_QUANTITY_FK1 FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(PROJECT_ID);
GO

ALTER TABLE BILL_OF_QUANTITY
 ADD  CONSTRAINT BILL_OF_QUANTITY_FK2 FOREIGN KEY(BOQ_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
GO

ALTER TABLE BILL_OF_QUANTITY
 ADD  CONSTRAINT BILL_OF_QUANTITY_FK3 FOREIGN KEY(ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
GO

ALTER TABLE PROJECT
 ADD  CONSTRAINT PROJECT_FK1 FOREIGN KEY(CLIENT_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK1 FOREIGN KEY(BOQ_ID) REFERENCES BILL_OF_QUANTITY(BOQ_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK2 FOREIGN KEY(UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK3 FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK4 FOREIGN KEY(BQD_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK5 FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID);
GO

ALTER TABLE BOQ_DETAIL
 ADD  CONSTRAINT BOQ_DETAIL_FK6 FOREIGN KEY(BQD_CREATION_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
GO


ALTER TABLE STORE
 ADD  CONSTRAINT STORE_FK1 FOREIGN KEY(ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
GO


ALTER TABLE TXN_HEADER
 ADD  CONSTRAINT TXN_HEADER_FK1 FOREIGN KEY(ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
GO

ALTER TABLE TXN_HEADER
 ADD  CONSTRAINT TXN_HEADER_FK2 FOREIGN KEY(STORE_ID) REFERENCES STORE(STORE_ID);
GO

ALTER TABLE TXN_HEADER ADD CONSTRAINT TXN_HEADER_FK3 FOREIGN KEY (TXHD_STATE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE TXN_HEADER ADD CONSTRAINT TXN_HEADER_FK4 FOREIGN KEY (TXHD_TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

--ALTER TABLE TXN_HEADER ADD CONSTRAINT TXN_HEADER_FK5 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
--go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK3 FOREIGN KEY (TXHD_ID) REFERENCES TXN_HEADER(TXHD_ID)
go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK4 FOREIGN KEY (TXDE_PROD_ID) REFERENCES PRODUCT(PROD_ID)
go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK5 FOREIGN KEY (TXDE_UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID)
go

ALTER TABLE TXN_DETAIL ADD CONSTRAINT TXN_DETAIL_FK6 FOREIGN KEY (TXDE_DETAIL_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go



ALTER TABLE PAYMENT_MEDIA ADD CONSTRAINT PAYMENT_MEDIA_FK1 FOREIGN KEY (MEDT_ID) REFERENCES MEDIA_TYPE(MEDT_ID)
go

ALTER TABLE PAYMENT_MEDIA ADD CONSTRAINT PAYMENT_MEDIA_FK2 FOREIGN KEY (LEGT_ID) REFERENCES LEGAL_TENDER(LEGT_ID)
go


ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
go

ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK3 FOREIGN KEY (TXHD_ID) REFERENCES TXN_HEADER(TXHD_ID)
go

ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK4 FOREIGN KEY (MEDT_ID) REFERENCES MEDIA_TYPE(MEDT_ID)
go

ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK5 FOREIGN KEY (PAYM_ID) REFERENCES PAYMENT_MEDIA(PAYM_ID)
go

ALTER TABLE TXN_MEDIA ADD CONSTRAINT TXN_MEDIA_FK6 FOREIGN KEY (TXMD_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE PURCHASE_ORDER_HEADER ADD CONSTRAINT POH_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PURCHASE_ORDER_HEADER ADD CONSTRAINT POH_FK2 FOREIGN KEY (POH_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE PURCHASE_ORDER_HEADER ADD CONSTRAINT POH_FK3 FOREIGN KEY (POH_CREATION_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE PURCHASE_ORDER_HEADER ADD CONSTRAINT POH_FK4 FOREIGN KEY (POH_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE PURCHASE_ORDER_HEADER ADD CONSTRAINT POH_FK5 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK1 FOREIGN KEY (POH_ID) REFERENCES PURCHASE_ORDER_HEADER(POH_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK2 FOREIGN KEY (SPRC_ID) REFERENCES SUPP_PROD_PRICE(SPRC_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK3 FOREIGN KEY (TXLV_ID) REFERENCES TAX_LEG_VARIANCE(TXLV_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK4 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK5 FOREIGN KEY (UNOM_ID_CONTENTS) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK6 FOREIGN KEY (POL_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE PURCHASE_LINE ADD CONSTRAINT PL_FK7 FOREIGN KEY (POL_CREATION_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK1 FOREIGN KEY (POH_ID) REFERENCES PURCHASE_ORDER_HEADER(POH_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK2 FOREIGN KEY (POL_ID) REFERENCES PURCHASE_LINE(POL_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK3 FOREIGN KEY (BOQ_ID) REFERENCES BILL_OF_QUANTITY(BOQ_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK4 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK5 FOREIGN KEY (BPQL_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE PO_BOQ_LINK ADD CONSTRAINT PO_BOQ_LINK_FK6 FOREIGN KEY (BOQ_DETAIL_ID) REFERENCES BOQ_DETAIL(BOQ_DETAIL_ID);
go

ALTER TABLE DELIVERY_NOTE_HEADER ADD CONSTRAINT DELIVERY_NOTE_HEADER_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE DELIVERY_NOTE_HEADER ADD CONSTRAINT DELIVERY_NOTE_HEADER_FK2 FOREIGN KEY (POH_ID) REFERENCES PURCHASE_ORDER_HEADER(POH_ID);
go

ALTER TABLE DELIVERY_NOTE_HEADER ADD CONSTRAINT DELIVERY_NOTE_HEADER_FK3 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
go

ALTER TABLE DELIVERY_NOTE_HEADER ADD CONSTRAINT DELIVERY_NOTE_HEADER_FK4 FOREIGN KEY (DELN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE DELIVERY_NOTE_HEADER ADD CONSTRAINT DELIVERY_NOTE_HEADER_FK5 FOREIGN KEY (DELN_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK1 FOREIGN KEY (DELN_ID) REFERENCES DELIVERY_NOTE_HEADER(DELN_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK3 FOREIGN KEY (SPRC_ID) REFERENCES SUPP_PROD_PRICE(SPRC_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK4 FOREIGN KEY (DLNL_CASE_SIZE) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK5 FOREIGN KEY (DLNL_PRODUCT_SIZE) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK6 FOREIGN KEY (RCVD_CASE_SIZE) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK7 FOREIGN KEY (RCVD_PRODUCT_SIZE) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK8 FOREIGN KEY (DLNL_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE DELIVERY_NOTE_LINE ADD CONSTRAINT DELIVERY_NOTE_LINE_FK9 FOREIGN KEY (TXLV_ID) REFERENCES TAX_LEG_VARIANCE(TXLV_ID);
go

ALTER TABLE PO_DEL_NOTE_LINK ADD CONSTRAINT PO_DEL_NOTE_LINK_FK1 FOREIGN KEY (POH_ID) REFERENCES PURCHASE_ORDER_HEADER(POH_ID);
go

ALTER TABLE PO_DEL_NOTE_LINK ADD CONSTRAINT PO_DEL_NOTE_LINK_FK2 FOREIGN KEY (DELN_ID) REFERENCES DELIVERY_NOTE_HEADER(DELN_ID);
go


ALTER TABLE CUSTOMER_CONTACT ADD CONSTRAINT CUSTOMER_CONTACT_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
go

ALTER TABLE CUSTOMER_CONTACT ADD CONSTRAINT CUSTOMER_CONTACT_FK2 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);
go

ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_FK1 FOREIGN KEY (CONTACT_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go


ALTER TABLE APP_USER_ROLE ADD CONSTRAINT APP_USER_ROLE_FK1 FOREIGN KEY (USR_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE APP_USER_ROLE ADD CONSTRAINT APP_USER_ROLE_FK2 FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE(ROLE_ID);
go


ALTER TABLE USER_ACCESS ADD CONSTRAINT USER_ACCESS_FK1 FOREIGN KEY (USR_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE USER_ACCESS ADD CONSTRAINT USER_ACCESS_FK2 FOREIGN KEY (ACPT_ID) REFERENCES ACCESS_POINT(ACPT_ID);
go


ALTER TABLE ROLE_ACCESS ADD CONSTRAINT ROLE_ACCESS_FK1 FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE(ROLE_ID);
go


ALTER TABLE ROLE_ACCESS ADD CONSTRAINT ROLE_ACCESS_FK2 FOREIGN KEY (ACPT_ID) REFERENCES ACCESS_POINT(ACPT_ID);
go

ALTER TABLE STOCK_LOCATION ADD CONSTRAINT STOCK_LOCATION_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_LOCATION ADD CONSTRAINT STOCK_LOCATION_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK2 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK4 FOREIGN KEY (ORGU_ID_LOCATION) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK5 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK6 FOREIGN KEY (STCK_COND) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK7 FOREIGN KEY (STCK_CAT) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK8 FOREIGN KEY (STCK_LOCN_ID) REFERENCES STOCK_LOCATION(STCK_LOCN_ID);
go

ALTER TABLE STOCK ADD CONSTRAINT STOCK_FK9 FOREIGN KEY (ORGU_ID_RESPBILITY) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK1 FOREIGN KEY (STCK_ID) REFERENCES STOCK(STCK_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK4 FOREIGN KEY (USR_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK5 FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK8 FOREIGN KEY (TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK9 FOREIGN KEY (STCK_COND) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK10 FOREIGN KEY (STCK_CAT) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK12 FOREIGN KEY (UNOM_ID) REFERENCES UNIT_OF_MEASURE(UNOM_ID);
go

ALTER TABLE STOCK_EVENT ADD CONSTRAINT STOCK_EVENT_FK14 FOREIGN KEY (STCK_LOCN_ID) REFERENCES STOCK_LOCATION(STCK_LOCN_ID);
go

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK1 FOREIGN KEY (TXHD_ID) REFERENCES TXN_HEADER(TXHD_ID);
go

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK3 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

--ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK4 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
--go

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK5 FOREIGN KEY (TXIV_TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go


ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT INVOICE_DETAIL_FK1 FOREIGN KEY (TXIV_ID) REFERENCES INVOICE(TXIV_ID);
go

ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT INVOICE_DETAIL_FK2 FOREIGN KEY (TXDE_ID) REFERENCES TXN_DETAIL(TXDE_ID);
go

ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT INVOICE_DETAIL_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT INVOICE_DETAIL_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT INVOICE_DETAIL_FK5 FOREIGN KEY (TXID_LINE_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go


ALTER TABLE INVOICE_MEDIA ADD CONSTRAINT INVOICE_MEDIA_FK1 FOREIGN KEY (TXIV_ID) REFERENCES INVOICE(TXIV_ID);
go

ALTER TABLE INVOICE_MEDIA ADD CONSTRAINT INVOICE_MEDIA_FK2 FOREIGN KEY (TXMD_ID) REFERENCES TXN_MEDIA(TXMD_ID);
go

ALTER TABLE INVOICE_MEDIA ADD CONSTRAINT INVOICE_MEDIA_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE INVOICE_MEDIA ADD CONSTRAINT INVOICE_MEDIA_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE INVOICE_MEDIA ADD CONSTRAINT INVOICE_MEDIA_FK5 FOREIGN KEY (TXIM_LINE_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE CUSTOMER_ACCOUNT_DEBT ADD CONSTRAINT CUSTOMER_ACCOUNT_DEBT_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
go

ALTER TABLE CUSTOMER_ACCOUNT_DEBT ADD CONSTRAINT CUSTOMER_ACCOUNT_DEBT_FK2 FOREIGN KEY (TXHD_ID) REFERENCES INVOICE(TXIV_ID);
go

ALTER TABLE TXN_ACC_PAYMENT ADD CONSTRAINT TXN_ACC_PAYMENT_FK1 FOREIGN KEY (TXHD_ID) REFERENCES TXN_HEADER(TXHD_ID);
go

ALTER TABLE TXN_ACC_PAYMENT ADD CONSTRAINT TXN_ACC_PAYMENT_FK2 FOREIGN KEY (CAD_ID) REFERENCES CUSTOMER_ACCOUNT_DEBT(CAD_ID);
go


ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK3 FOREIGN KEY (CSSN_OPERATOR) REFERENCES APP_USER(USR_ID);
go


ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK4 FOREIGN KEY (CSSN_STATUS) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK5 FOREIGN KEY (CSSN_METHOD_OPEN) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK6 FOREIGN KEY (CSSN_METHOD_CLOSE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE CASH_SESSION ADD CONSTRAINT CASH_SESSION_FK7 FOREIGN KEY (CSSN_CYCLE_PERIOD) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE SESSION_EVENT ADD CONSTRAINT SESSION_EVENT_FK1 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE SESSION_EVENT ADD CONSTRAINT SESSION_EVENT_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE SESSION_EVENT ADD CONSTRAINT SESSION_EVENT_FK3 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE SESSION_EVENT ADD CONSTRAINT SESSION_EVENT_FK4 FOREIGN KEY (SEEV_EVENT_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE SESSION_EVENT ADD CONSTRAINT SESSION_EVENT_FK5 FOREIGN KEY (SEEV_OPERATOR) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK1 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK2 FOREIGN KEY (SEEV_ID) REFERENCES SESSION_EVENT(SEEV_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK5 FOREIGN KEY (MEDT_ID) REFERENCES MEDIA_TYPE(MEDT_ID);
go

ALTER TABLE SESSION_MEDIA ADD CONSTRAINT SESSION_MEDIA_FK6 FOREIGN KEY (PAYM_ID) REFERENCES PAYMENT_MEDIA(PAYM_ID);
go


ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK1 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK2 FOREIGN KEY (SEEV_ID) REFERENCES SESSION_EVENT(SEEV_ID);
go

ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK5 FOREIGN KEY (MEDT_ID) REFERENCES MEDIA_TYPE(MEDT_ID);
go

ALTER TABLE SESSION_EVENT_DETAIL ADD CONSTRAINT SESSION_EVENT_DETAIL_FK6 FOREIGN KEY (PAYM_ID) REFERENCES PAYMENT_MEDIA(PAYM_ID);
go


ALTER TABLE SESSION_TOTAL ADD CONSTRAINT SESSION_TOTAL_FK1 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE SESSION_TOTAL ADD CONSTRAINT SESSION_TOTAL_FK2 FOREIGN KEY (MEDT_ID) REFERENCES MEDIA_TYPE(MEDT_ID);
go

ALTER TABLE SESSION_TOTAL ADD CONSTRAINT SESSION_TOTAL_FK3 FOREIGN KEY (PAYM_ID) REFERENCES PAYMENT_MEDIA(PAYM_ID);
go

ALTER TABLE SESSION_TOTAL ADD CONSTRAINT SESSION_TOTAL_UK1 UNIQUE(CSSN_SESSION_ID,
   MEDT_ID,
   PAYM_ID)
go



ALTER TABLE TXN_SESSION_LINK ADD CONSTRAINT TXN_SESSION_LINK_FK1 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE TXN_SESSION_LINK ADD CONSTRAINT TXN_SESSION_LINK_FK2 FOREIGN KEY (TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE TXN_SESSION_LINK ADD CONSTRAINT TXN_SESSION_LINK_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go
ALTER TABLE TXN_SESSION_LINK ADD CONSTRAINT TXN_SESSION_LINK_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go


ALTER TABLE TOTAL_SALE_OPERATOR ADD CONSTRAINT TOTAL_SALE_OPERATOR_FK1 FOREIGN KEY (TOOP_OPERATOR) REFERENCES app_user(USR_ID);
go

ALTER TABLE TOTAL_SALE_OPERATOR ADD CONSTRAINT TOTAL_SALE_OPERATOR_FK2 FOREIGN KEY (TOOP_TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE TOTAL_SALE_OPERATOR ADD CONSTRAINT TOTAL_SALE_OPERATOR_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE TOTAL_SALE_OPERATOR ADD CONSTRAINT TOTAL_SALE_OPERATOR_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go


ALTER TABLE TOTAL_TAX_GROUP ADD CONSTRAINT TOTAL_TAX_GROUP_FK1 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE TOTAL_TAX_GROUP ADD CONSTRAINT TOTAL_TAX_GROUP_FK2 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE TOTAL_TAX_GROUP ADD CONSTRAINT TOTAL_TAX_GROUP_FK3 FOREIGN KEY (TOTG_TXRL_ID) REFERENCES TAX_LEG_VARIANCE(TXLV_ID);
go


ALTER TABLE TOTAL_MEDIA_OPERATOR ADD CONSTRAINT TOTAL_MEDIA_OPERATOR_FK1 FOREIGN KEY (TOMO_OPERATOR) REFERENCES app_user(USR_ID);
go

ALTER TABLE TOTAL_MEDIA_OPERATOR ADD CONSTRAINT TOTAL_MEDIA_OPERATOR_FK3 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE TOTAL_MEDIA_OPERATOR ADD CONSTRAINT TOTAL_MEDIA_OPERATOR_FK4 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_FK2 FOREIGN KEY (ACC_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE JOURNAL_ENTRY ADD CONSTRAINT JOURNAL_ENTRY_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE JOURNAL_ENTRY ADD CONSTRAINT JOURNAL_ENTRY_FK2 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

ALTER TABLE JOURNAL_ENTRY ADD CONSTRAINT JOURNAL_ENTRY_FK3 FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID);
go

ALTER TABLE JOURNAL_ENTRY ADD CONSTRAINT JOURNAL_ENTRY_FK4 FOREIGN KEY (APP_USER_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE JOURNAL_SUPPORT ADD CONSTRAINT JOURNAL_SUPPORT_FK1 FOREIGN KEY (JRN_ID) REFERENCES JOURNAL_ENTRY(JRN_ID);
go

ALTER TABLE JOURNAL_SUPPORT ADD CONSTRAINT JOURNAL_SUPPORT_FK2 FOREIGN KEY (TXMD_ID) REFERENCES TXN_MEDIA(TXMD_ID);
go


ALTER TABLE JOURNAL_RULE ADD CONSTRAINT JOURNAL_RULE_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE JOURNAL_RULE ADD CONSTRAINT JOURNAL_RULE_FK2 FOREIGN KEY (TXN_TYPE) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go

ALTER TABLE JOURNAL_RULE ADD CONSTRAINT JOURNAL_RULE_FK3 FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT(ACC_ID);
go

ALTER TABLE JOURNAL_RULE ADD CONSTRAINT JOURNAL_RULE_FK4 FOREIGN KEY (JRNR_ACTION) REFERENCES CONFIG_CATEGORY(CATEGORY_ID);
go


ALTER TABLE ACCOUNTING_EXPORT ADD CONSTRAINT ACCOUNTING_EXPORT_FK1 FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID);
go

ALTER TABLE ACCOUNTING_EXPORT ADD CONSTRAINT ACCOUNTING_EXPORT_FK2 FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID);
go

ALTER TABLE ACCOUNTING_EXPORT ADD CONSTRAINT ACCOUNTING_EXPORT_FK3 FOREIGN KEY (APP_USER_ID) REFERENCES APP_USER(USR_ID);
go

ALTER TABLE ACC_EXPORT_SUPP_LINK ADD CONSTRAINT ACC_EXPORT_SUPP_LINK_FK1 FOREIGN KEY (ACC_EXP_ID) REFERENCES ACCOUNTING_EXPORT(ACC_EXP_ID);
go

ALTER TABLE ACC_EXPORT_SUPP_LINK ADD CONSTRAINT ACC_EXPORT_SUPP_LINK_FK2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID);
go


ALTER TABLE ACC_EXPORT_DELN_LINK ADD CONSTRAINT ACC_EXPORT_DELN_LINK_FK1 FOREIGN KEY (ACC_EXP_ID) REFERENCES ACCOUNTING_EXPORT(ACC_EXP_ID);
go

ALTER TABLE ACC_EXPORT_DELN_LINK ADD CONSTRAINT ACC_EXPORT_DELN_LINK_FK2 FOREIGN KEY (DELN_ID) REFERENCES DELIVERY_NOTE_HEADER(DELN_ID);
go


ALTER TABLE ACC_EXPORT_SESSION_LINK ADD CONSTRAINT ACC_EXPORT_SESSION_LINK_FK1 FOREIGN KEY (ACC_EXP_ID) REFERENCES ACCOUNTING_EXPORT(ACC_EXP_ID);
go


ALTER TABLE ACC_EXPORT_SESSION_LINK ADD CONSTRAINT ACC_EXPORT_SESSION_LINK_FK2 FOREIGN KEY (CSSN_SESSION_ID) REFERENCES CASH_SESSION(CSSN_SESSION_ID);
go

--INDEXES
CREATE INDEX SUPP_IX1 ON SUPPLIER
(SUPPLIER_CODE)
go

CREATE INDEX SUPP_IX2 ON SUPPLIER
(SUPPLIER_CODE)
go


CREATE INDEX LEGT_IX1 ON LEGAL_TENDER
(LEGT_FROM_DATE)
go

CREATE INDEX LEGT_IX2 ON LEGAL_TENDER
(LEGT_TO_DATE)
go

CREATE INDEX PRIB_IX1 ON PRICE_BAND
(ORGU_ID)
go

CREATE INDEX PRIB_IX3 ON PRICE_BAND
(LEGT_ID)
go

CREATE INDEX ORGU_IX3 ON ORG_UNIT
(COMP_ID)
go

CREATE INDEX ORGU_IX8 ON ORG_UNIT
(ORGU_CODE)
go

CREATE INDEX ORGU_IX7 ON ORG_UNIT
(PRIB_ID)
go

CREATE INDEX ORGU_IX5 ON ORG_UNIT
(ORGT_TYPE_ID)
go

CREATE INDEX ORGU_IX2 ON ORG_UNIT
(WARH_ID)
go

CREATE INDEX ORGU_IX9 ON ORG_UNIT
(PRIB_ID_COST)
go

CREATE INDEX ORGU_IX6 ON ORG_UNIT
(ORGU_DEF_LEGT_ID)
go

CREATE INDEX ORGUIX10 ON ORG_UNIT
(ORGU_DEF_LANG_ID)
go

CREATE INDEX PSTR_IX1 ON PRODGP_STRUCTURE
(ORGU_ID)
go

CREATE INDEX PSTR_IX5 ON PRODGP_STRUCTURE
(PSTR_IS_LIVE)
go

CREATE INDEX PSTR_IX3 ON PRODGP_STRUCTURE
(PSTR_DATE_FROM)
go

CREATE INDEX PSTR_IX6 ON PRODGP_STRUCTURE
(LOCN_ID)
go

CREATE INDEX PSTR_IX4 ON PRODGP_STRUCTURE
(PSTR_DATE_TO)
go

CREATE INDEX PSTR_IX2 ON PRODGP_STRUCTURE
(PSTR_CONSTANT)
go

CREATE INDEX PGPT_IX5 ON PRODGP_STRUCTURE_DETAIL
(PRGT_ID)
go

CREATE INDEX PGPT_IX4 ON PRODGP_STRUCTURE_DETAIL
(PSTR_ID)
go

CREATE INDEX PGPT_IX3 ON PRODGP_STRUCTURE_DETAIL
(PGSD_ID_PARENT)
go

CREATE INDEX PRGP_IX4 ON PRODUCT_GROUP
(PRGP_MAIN_PRGP_ID)
go

CREATE INDEX PGSL_IX4 ON PRODGP_STR_LINK
(PRGP_CHILD_ID)
go

CREATE INDEX PGSL_IX3 ON PRODGP_STR_LINK
(PRGP_PARENT_ID)
go

CREATE INDEX PGSL_IX1 ON PRODGP_STR_LINK
(PRGP_ID)
go

CREATE INDEX PGSL_IX5 ON PRODGP_STR_LINK
(PGSD_ID)
go

CREATE INDEX TXRN_IX1 ON TAX_RULE_NAME
(TXRN_NAME)
go


CREATE INDEX TXRL_IX3 ON TAX_RULE
(TXRN_ID)
go

CREATE INDEX TXRL_IX4 ON TAX_RULE
(TXRL_CODE)
go

CREATE INDEX TXLV_IX4 ON TAX_LEG_VARIANCE
(TXLV_DATETIME_FROM)
go

CREATE INDEX TXLV_IX1 ON TAX_LEG_VARIANCE
(TXRL_ID)
go

CREATE INDEX TXLV_IX5 ON TAX_LEG_VARIANCE
(TXLV_DATETIME_TO)
go

CREATE INDEX UNOM_IX1 ON UNIT_OF_MEASURE
(UNOM_CODE)
go

CREATE INDEX PROD_IX1 ON PRODUCT
(ORGU_ID_OWNING)
go

CREATE INDEX PROD_IX7 ON PRODUCT
(PROD_SKU)
go

CREATE INDEX PROD_IX2 ON PRODUCT
(PROD_NAME)
go

CREATE INDEX PROU_IX3 ON PROD_ORGU_LINK
(PROD_ID)
go


CREATE INDEX PROU_IX2 ON PROD_ORGU_LINK
(ORGU_ID)
go

CREATE INDEX TXHDIX01 ON TXN_HEADER
(TXHD_TXN_TYPE)
go

CREATE INDEX TXHDIX02 ON TXN_HEADER
(TXHD_TXN_NR)
go

CREATE INDEX TXHDIX03 ON TXN_HEADER
(TXHD_STATE)
go

CREATE INDEX TXHDIX04 ON TXN_HEADER
(ORGU_ID)
go

CREATE INDEX TXHDIX05 ON TXN_HEADER
(STORE_ID)
go

CREATE INDEX TXHDIX06 ON TXN_HEADER
(CUSTOMER_ID)
go


CREATE INDEX TXN_DETAIL_IX01 ON TXN_DETAIL
(ORGU_ID)
go
CREATE INDEX TXN_DETAIL_IX02 ON TXN_DETAIL
(STORE_ID)
go

CREATE INDEX TXN_DETAIL_IX03 ON TXN_DETAIL
(TXHD_ID)
go

CREATE INDEX MEDIA_TYPE_IX01 ON MEDIA_TYPE
(MEDT_NAME)
go

CREATE INDEX MEDIA_TYPE_IX02 ON MEDIA_TYPE
(MEDT_CODE)
go

CREATE INDEX PAYMENT_MEDIA_IX01 ON PAYMENT_MEDIA
(PAYM_CODE)
go

CREATE INDEX PAYMENT_MEDIA_IX02 ON PAYMENT_MEDIA
(PAYM_NAME)
go

CREATE INDEX TXN_MEDIA_IX01 ON TXN_MEDIA
(ORGU_ID)
go
CREATE INDEX TXN_MEDIA_IX02 ON TXN_MEDIA
(STORE_ID)
go

CREATE INDEX TXN_MEDIA_IX03 ON TXN_MEDIA
(TXHD_ID)
go

CREATE INDEX TXN_MEDIA_IX04 ON TXN_MEDIA
(TXMD_TYPE)
go


CREATE INDEX POH_IX01 ON PURCHASE_ORDER_HEADER
(SUPPLIER_ID)
go

CREATE INDEX POH_IX02 ON PURCHASE_ORDER_HEADER
(POH_ORDER_NUMBER)
go

CREATE INDEX POH_IX03 ON PURCHASE_ORDER_HEADER
(POH_DELV_DATE)
go

CREATE INDEX POH_IX04 ON PURCHASE_ORDER_HEADER
(ORGU_ID)
go

CREATE INDEX POH_IX05 ON PURCHASE_ORDER_HEADER
(POH_STATUS)
go

CREATE INDEX POH_IX06 ON PURCHASE_ORDER_HEADER
(POH_TYPE)
go

CREATE INDEX POL_IX01 ON PURCHASE_LINE
(POH_ID)
go


CREATE INDEX POL_IX02 ON PURCHASE_LINE
(POH_ORDER_NUMBER)
go

CREATE INDEX POL_IX03 ON PURCHASE_LINE
(SPRC_ID)
go

CREATE INDEX POL_IX04 ON PURCHASE_LINE
(POL_DATE_RECEIVED)
go

CREATE INDEX POL_IX05 ON PURCHASE_LINE
(POL_STATUS)
go

CREATE INDEX DELN_HEADER_IX01 ON DELIVERY_NOTE_HEADER
(ORGU_ID)
go

CREATE INDEX DELN_HEADER_IX02 ON DELIVERY_NOTE_HEADER
(DELN_NOTE_NUMBER)
go

CREATE INDEX DELN_HEADER_IX03 ON DELIVERY_NOTE_HEADER
(DELN_GRN)
go

CREATE INDEX DELN_HEADER_IX04 ON DELIVERY_NOTE_HEADER
(POH_ID)
go

CREATE INDEX DELN_HEADER_IX05 ON DELIVERY_NOTE_HEADER
(POH_ORDER_NUMBER)
go

CREATE INDEX DELN_HEADER_IX06 ON DELIVERY_NOTE_HEADER
(SUPPLIER_ID)
go

CREATE INDEX DELN_HEADER_IX07 ON DELIVERY_NOTE_HEADER
(DELN_DELIVERY_DATE)
go

CREATE INDEX DELN_HEADER_IX08 ON DELIVERY_NOTE_HEADER
(DELN_STATUS)
go

CREATE INDEX PO_DEL_NOTE_LINK_IDX0 ON PO_DEL_NOTE_LINK
(POH_ORDER_NUMBER)
go

CREATE INDEX PO_DEL_NOTE_LINK_IDX1 ON PO_DEL_NOTE_LINK
(DELN_NOTE_NUMBER)
go

CREATE INDEX PO_DEL_NOTE_LINK_IDX2 ON PO_DEL_NOTE_LINK
(DELN_GRN)
go

CREATE INDEX PO_DEL_NOTE_LINK_IDX3 ON PO_DEL_NOTE_LINK
(DELN_ID)
go

CREATE INDEX PO_DEL_NOTE_LINK_IDX4 ON PO_DEL_NOTE_LINK
(POH_ID)
go

CREATE INDEX APP_USER_IDX1 ON APP_USER
(USR_NAME)
go

CREATE INDEX APP_USER_IDX2 ON APP_USER
(USR_PASS)
go

CREATE INDEX STOCK_LOCATION_IDX1 ON STOCK_LOCATION
(STCK_LOCN_NAME)
go

CREATE INDEX STOCK_IDX1 ON STOCK
(PROD_ID)
go

CREATE INDEX STOCK_IDX2 ON STOCK
(ORGU_ID_LOCATION)
go


CREATE INDEX STOCK_IDX3 ON STOCK
(STCK_COND)
go

CREATE INDEX STOCK_IDX4 ON STOCK
(STCK_CAT)
go

CREATE INDEX STOCK_IDX5 ON STOCK
(STCK_LOCN_ID)
go


CREATE INDEX STOCK_EVENT_IDX1 ON STOCK_EVENT
(STCK_ID)
go

CREATE INDEX STOCK_EVENT_IDX2 ON STOCK_EVENT
(ORGU_ID)
go

CREATE INDEX STOCK_EVENT_IDX3 ON STOCK_EVENT
(STORE_ID)
go

CREATE INDEX STOCK_EVENT_IDX4 ON STOCK_EVENT
(USR_ID)
go

CREATE INDEX STOCK_EVENT_IDX5 ON STOCK_EVENT
(PROD_ID)
go

CREATE INDEX STOCK_EVENT_IDX6 ON STOCK_EVENT
(STCK_EVNT_DATE)
go

CREATE INDEX STOCK_EVENT_IDX7 ON STOCK_EVENT
(TXN_DATE)
go

CREATE INDEX STOCK_EVENT_IDX8 ON STOCK_EVENT
(TXN_TYPE)
go

CREATE INDEX STOCK_EVENT_IDX9 ON STOCK_EVENT
(TXN_NUMBER)
go

CREATE INDEX STOCK_EVENT_IDX10 ON STOCK_EVENT
(STCK_COND)
go

CREATE INDEX STOCK_EVENT_IDX11 ON STOCK_EVENT
(STCK_CAT)
go

CREATE INDEX TOTAL_SALE_OPERATOR_IDX1 ON TOTAL_SALE_OPERATOR
(TOOP_OPERATOR)
go

CREATE INDEX TOTAL_SALE_OPERATOR_IDX2 ON TOTAL_SALE_OPERATOR
(TOOP_TXN_TYPE)
go

CREATE INDEX TOTAL_SALE_OPERATOR_IDX3 ON TOTAL_SALE_OPERATOR
(ORGU_ID)
go

CREATE INDEX TOTAL_SALE_OPERATOR_IDX4 ON TOTAL_SALE_OPERATOR
(STORE_ID)
go

CREATE INDEX TOTAL_SALE_OPERATOR_IDX5 ON TOTAL_SALE_OPERATOR
(TOOP_TRADING_DATE)
go

CREATE INDEX TOTAL_TAX_GROUP_IDX1 ON TOTAL_TAX_GROUP
(ORGU_ID)
go

CREATE INDEX TOTAL_TAX_GROUP_IDX2 ON TOTAL_TAX_GROUP
(STORE_ID)
go

CREATE INDEX TOTAL_TAX_GROUP_IDX3 ON TOTAL_TAX_GROUP
(TOTG_TXRL_ID)
go

CREATE INDEX TOTAL_TAX_GROUP_IDX4 ON TOTAL_TAX_GROUP
(TOTG_TRADING_DATE)
go

CREATE INDEX TOTAL_TAX_GROUP_IDX5 ON TOTAL_TAX_GROUP
(TOTG_TXGP_CODE)
go


CREATE INDEX TOTAL_MEDIA_OPERATOR_IDX1 ON TOTAL_MEDIA_OPERATOR
(TOMO_OPERATOR)
go

CREATE INDEX TOTAL_MEDIA_OPERATOR_IDX2 ON TOTAL_MEDIA_OPERATOR
(ORGU_ID)
go

CREATE INDEX TOTAL_MEDIA_OPERATOR_IDX3 ON TOTAL_MEDIA_OPERATOR
(STORE_ID)
go

CREATE INDEX TOTAL_MEDIA_OPERATOR_IDX4 ON TOTAL_MEDIA_OPERATOR
(TOMO_TRADING_DATE)
go

CREATE INDEX TOTAL_MEDIA_OPERATOR_IDX5 ON TOTAL_MEDIA_OPERATOR
(PAYM_ID)
go

--UNIQUE CONSTRAINT:

Alter table CONFIG_CATEGORY
  ADD UNIQUE (CATEGORY_CODE)
GO

Alter table APP_USER
  ADD UNIQUE (USR_NAME)
GO

Alter table APP_ROLE
  ADD UNIQUE (ROLE_NAME)
GO

Alter table APP_ROLE
  ADD UNIQUE (ROLE_CODE)
GO



