USE [RETAIL]
GO

CREATE TABLE [dbo].[CONFIG_TYPE](
	[CONFIG_TYPE_ID] [int] IDENTITY (1,1) NOT NULL,
	[CONFIG_CODE] [varchar](100) NOT NULL,
	[DISPLAY_NAME] [varchar](200) NOT NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[CATEGORY_ORDER] [int] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CONFIG_CATEGORY](
	[CATEGORY_ID] [bigint] IDENTITY (1,1) NOT NULL,
	[CONFIG_TYPE_ID] [int] NOT NULL,
	[CATEGORY_CODE] [varchar](100) NULL,
	[DISPLAY_NAME] [varchar](200) NOT NULL,
	[CATEGORY_ORDER] [int] ,
	[DESCRIPTION] [varchar](500) NULL
) ON [PRIMARY]


CREATE TABLE [dbo].[Customer](
	[CUSTOMER_ID] [bigint] IDENTITY (1,1) NOT NULL,
	[Customer_Type] [varchar](100) NULL,
	[First_Name] [varchar](100) NULL,
	[Sur_Name] [varchar](100) NULL,
	[Middle_Name] [varchar](100) NULL,
	[Company_Name] [nchar](100) NULL,
	[Date_Of_Birth] [datetime] NULL,
	[Address] [varchar](500) NULL,
	[E_Mail] [varchar](100) NULL,
	[Mobile] [varchar](20) NULL,
	[Phone] [varchar](20) NULL,
	[Web_Site] [nchar](100) NULL,
	[Code] [varchar](100) NULL,
	[Title] [varchar](10) NULL,
	[Fax] [varchar](20) NULL,
	[Grade_Id] [int] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CUSTOMER_GRADE](
	[GRADE_ID] [int] IDENTITY (1,1) NOT NULL,
	[GRADE_CODE] [varchar](20) NULL,
	[GRADE_NAME] [varchar](200) NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[RATE] [NUMERIC ] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CONTACT](
	[CONTACT_ID] [bigint] IDENTITY (1,1) NOT NULL,
	[COUNTRY] [varchar](100) NULL,
	[STATE] [varchar](100) NULL,
	[POST_CODE] [varchar](20) NULL,
	[ADDRESS1] [varchar](200) NULL,
	[ADDRESS2] [varchar](200) NULL,
	[E_MAIL] [varchar](100) NULL,
	[MOBILE] [varchar](20) NULL,
	[PHONE] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[WEB_SITE] [nchar](100) NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[SUPPLIER](
	[SUPPLIER_ID] [bigint] IDENTITY (1,1) NOT NULL,
	[SUPPLIER_CODE] [varchar](50) NOT NULL,
	[SUPPLIER_NAME] [varchar](100) NOT NULL,
	[SUPPLIER_TYPE_ID] [bigint] NULL,
	[SUPPLIER_STATUS_ID] [bigint] NULL,
	[CONTACT_ID] [bigint] NULL,
	[LEAD_TIME] [int] NULL,
	[STOCK_COVER] [int] NULL,
	[MIN_ORDER_VALUE] [decimal](19,4) NULL,
	[CREDIT_LIMIT] [decimal](19,4) NULL,
	[MAX_ADV_ORDER] [int] NULL,
	[LAST_MODIFIED_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL,
	[LAST_MODIFIED_BY] [bigint] NULL,
	[CONTACT_FIRST_NAME] [varchar](100) NULL,
	[CONTACT_SUR_NAME] [varchar](100) NULL,
	[CONTACT_TITLE] [varchar](20) NULL,
	[CONTACT_KNOWN_AS] [varchar](100) NULL
) ON [PRIMARY]

CREATE TABLE COMPANY(
    COMP_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    COMP_IS_TRADING DECIMAL(31,0),
    COMP_OPEN_DATE datetime,
    COMP_CLOSE_DATE datetime,
    COMP_CHQ_PAYEE VARCHAR(60),
    COMP_STK_AUTH_VAL DECIMAL(31,6),
    COMP_TRADE_CUTOFF datetime,
    COMP_PWRD_VALIDITY DECIMAL(31,0),
    COMP_LOGOFF_PERIOD DECIMAL(31,0) DEFAULT 0 NOT NULL,
    COMP_FORCECRDSWIPE DECIMAL(31,0) DEFAULT 0 NOT NULL,
    COMP_SECURE_LOGOFF DECIMAL(31,0) DEFAULT 0 NOT NULL,
    COMP_SDC_ISSUER SMALLINT,
    COMP_PWD_RETRY DECIMAL(31,0) DEFAULT 3 NOT NULL,
    COMP_REF_DUP_RCPT DECIMAL(31,0),
    COMP_RECON_ATTEMPT DECIMAL(31,0),
    COMP_REFUND_DAYS DECIMAL(31,0),
    COMP_REFUND_START datetime,
    COMP_REFUND_EXPIRY datetime,
    COMP_REFUND_DAYSGR DECIMAL(31,0),
    COMP_REFUND_POLICY VARCHAR(255),
    COMP_DISC_TAX_RULE DECIMAL(31,0) DEFAULT 0 NOT NULL,
    COMP_CVOUCH_DAYS DECIMAL(31,0),
    COMP_CVOUCH_POLICY VARCHAR(2048),
    COMP_GRACE_LIMIT DECIMAL(31,0) DEFAULT 0 NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);

CREATE TABLE ORG_TYPE(
    ORGT_TYPE_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    ORGT_TYPE_NAME VARCHAR(60) NOT NULL,
    ORGT_TYPE_CODE VARCHAR(20) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);


CREATE TABLE ORG_UNIT(
    ORGU_ID DECIMAL(31,0)IDENTITY (1,1) NOT NULL,
    ORGU_NAME VARCHAR(60) NOT NULL,
    ORGU_DESC VARCHAR(2048),
    ORGU_CODE VARCHAR(10) NOT NULL,
    ORGT_TYPE_ID DECIMAL(31,0) NOT NULL,
    ORGU_SHORT_NAME VARCHAR(15),
    PRIB_ID DECIMAL(31,0),
    WARH_ID DECIMAL(31,0),
    OUTL_ID DECIMAL(31,0),
    COMP_ID DECIMAL(31,0),
    ORGU_DEF_LEGT_ID DECIMAL(31,0),
    ORGU_CREATED datetime,
    ORGU_MODIFIED datetime,
    ORGU_NEXT_PO FLOAT,
    ORGU_AUDIT_LEVEL DECIMAL(31,0),
    ORGU_SOFTWARE VARCHAR(10),
    ORGU_VAT_REG_NO VARCHAR(100),
    AIRP_ID DECIMAL(31,0),
    PRIB_ID_COST DECIMAL(31,0),
    ORGU_WEEE_REG_NO VARCHAR(100),
    ORGU_DEF_LANG_ID DECIMAL(31,0),
    ORGU_TIME_ZONE VARCHAR(60),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);

CREATE TABLE STORE(
    ORGU_ID DECIMAL(31,0) NOT NULL,
    COMPANYCODE VARCHAR(10) NOT NULL,
    STORECODE VARCHAR(10) NOT NULL,
    NAME VARCHAR(30),
    STORESTATUS INTEGER,
    STORE_GROUP_ID VARCHAR(10),
    BANNER VARCHAR(255),
    MARQUEE VARCHAR(255),
    RECEIPTHDR1 VARCHAR(40),
    RECEIPTHDR2 VARCHAR(40),
    RECEIPTHDR3 VARCHAR(40),
    RECEIPTHDR4 VARCHAR(40),
    RECEIPTHDR5 VARCHAR(40),
    RECEIPTHDR6 VARCHAR(40),
    HDRBOLD SMALLINT DEFAULT 1 NOT NULL,
    HDRDBLHT SMALLINT NOT NULL,
    HDRDBLW SMALLINT NOT NULL,
    RECEIPTFOOT1 VARCHAR(40),
    RECEIPTFOOT2 VARCHAR(40),
    RECEIPTFOOT3 VARCHAR(40),
    RECEIPTFOOT4 VARCHAR(40),
    RECEIPTFOOT5 VARCHAR(40),
    RECEIPTFOOT6 VARCHAR(40),
    FOOTBOLD SMALLINT DEFAULT 1 NOT NULL,
    FOOTDBLHT SMALLINT DEFAULT 0 NOT NULL,
    FOOTDBLW SMALLINT DEFAULT 0 NOT NULL,
    CHEQUEPAYEE VARCHAR(60),
    TRADINGDATE datetime,
    EUROLAND SMALLINT,
    STOCK_AUTH_VALUE DECIMAL(20,6),
    VATREGNUMBER VARCHAR(100),
    IN_PROGRESS_MSG VARCHAR(255),
    BETWEEN_TXN_MSG VARCHAR(255),
    SECURE_MODE_MSG VARCHAR(255),
    ADDRESS1 VARCHAR(100),
    ADDRESS2 VARCHAR(100),
    ADDRESS3 VARCHAR(100),
    ADDRESS4 VARCHAR(100),
    ADDRESS5 VARCHAR(100),
    POSTCODE VARCHAR(100),
    EMAIL VARCHAR(256),
    SINVHDR1 VARCHAR(40),
    SINVHDR2 VARCHAR(40),
    SINVHDR3 VARCHAR(40),
    SINVHDR4 VARCHAR(40),
    SINVHDR5 VARCHAR(40),
    SINVHDR6 VARCHAR(40),
    SINVFOOT1 VARCHAR(40),
    SINVFOOT2 VARCHAR(40),
    SINVFOOT3 VARCHAR(40),
    SINVFOOT4 VARCHAR(40),
    SINVFOOT5 VARCHAR(40),
    SINVFOOT6 VARCHAR(40),
    GEOR_ID DECIMAL(31,0),
    BANK_ACCOUNT_NR VARCHAR(100),
    BANK_NAME VARCHAR(60),
    REFUND_DAYS DECIMAL(31,0),
    REFUND_START datetime,
    REFUND_EXPIRY datetime,
    REFUND_DAYSGR DECIMAL(31,0),
    REFUND_POLICY VARCHAR(255),
    TELEPHONE VARCHAR(100),
    WEEEREGNUMBER VARCHAR(100),
    CREDITVOUCH_DAYS DECIMAL(31,0),
    CREDITVOUCH_POLICY VARCHAR(255),
    PASSWORD_DORMANT DECIMAL(31,0) DEFAULT 0 NOT NULL,
    URL VARCHAR(2048),
    STORETYPE DECIMAL(31,0) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0
);


--product group type
CREATE TABLE PRGP_TYPE(
    PRGT_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PRGT_CODE VARCHAR(10) NOT NULL,
    PRGT_NAME VARCHAR(60) NOT NULL,
    PRGT_TYPE_CONST DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);

--product group structure
CREATE TABLE PRODGP_STRUCTURE(
    PSTR_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PSTR_NAME VARCHAR(60) NOT NULL,
    PSTR_DESC VARCHAR(2048),
    PSTR_DATE_FROM datetime ,
    PSTR_DATE_TO datetime ,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PSTR_IS_LIVE DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PSTR_MAX_LEVELS DECIMAL(31,0),
    PSTR_CONSTANT DECIMAL(31,0),
    LOCN_ID DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);
-- define hierarchy of product group structure
CREATE TABLE PRODGP_STRUCTURE_DETAIL(
    PGSD_ID DECIMAL(31,0) IDENTITY (1,1) NOT NULL,
    PGSD_LEVEL_NAME VARCHAR(60) NOT NULL,
    PGSD_LEVEL_DESC VARCHAR(2048),
    PGSD_ID_PARENT DECIMAL(31,0),
    PGSD_LEVEL DECIMAL(31,0) NOT NULL,
    PGSD_MANDATORY DECIMAL(31,0) DEFAULT 1 NOT NULL,
    PSTR_ID DECIMAL(31,0) NOT NULL,
    PRGT_ID DECIMAL(31,0) NOT NULL,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);

CREATE TABLE PRODUCT_GROUP(
    PRGP_ID DECIMAL(31,0) IDENTITY(1,1) NOT NULL,
    ORGU_ID DECIMAL(31,0) NOT NULL,
    PRGP_CODE VARCHAR(60) NOT NULL,
    PRGT_ID DECIMAL(31,0) NOT NULL,
    PRGP_DESC VARCHAR(2048),
    PRGP_NAME VARCHAR(60) NOT NULL,
    PRGP_CREATED datetime,
    PRGP_MODIFIED datetime,
    PRGP_CAN_BE_MERCH DECIMAL(31,0) DEFAULT 0 NOT NULL,
    PRGP_MAIN_PRGP_ID DECIMAL(31,0),
    PRGP_TRADE_START datetime,
    PRGP_TRADE_END datetime,
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);


CREATE TABLE PRODGP_STR_LINK(
    PGSL_ID DECIMAL(31,0)IDENTITY(1,1) NOT NULL,
    PGSL_CAN_BE_RANGED DECIMAL(31,0) DEFAULT 1 NOT NULL,
    PRGP_ID DECIMAL(31,0) NOT NULL,
    PSTR_ID DECIMAL(31,0) NOT NULL,
    PRGP_PARENT_ID DECIMAL(31,0),
    PRGP_CHILD_ID DECIMAL(31,0),
    PGSL_DISPLAY_SEQ DECIMAL(31,0),
    PGSD_ID DECIMAL(31,0),
    LCOUNT DECIMAL(31,0) DEFAULT 0 NOT NULL
);


ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
go

ALTER TABLE CUSTOMER_GRADE ADD CONSTRAINT GRADE_PK PRIMARY KEY(GRADE_ID)
go

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_2GRADE_FK FOREIGN KEY (GRADE_ID) REFERENCES CUSTOMER_GRADE(GRADE_ID)
go
ALTER TABLE CONFIG_TYPE ADD CONSTRAINT CONFIG_TYPE_PK PRIMARY KEY(CONFIG_TYPE_ID)
go

ALTER TABLE CONFIG_CATEGORY ADD CONSTRAINT CATEGORY_PK PRIMARY KEY(CATEGORY_ID)
go

ALTER TABLE CONFIG_CATEGORY ADD CONSTRAINT CATEGORY_2TYPE_FK FOREIGN KEY (CONFIG_TYPE_ID) REFERENCES CONFIG_TYPE(CONFIG_TYPE_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY(SUPPLIER_ID)
go

ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_PK PRIMARY KEY(CONTACT_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_TYEP_ID_2CATEGORY_FK FOREIGN KEY (SUPPLIER_TYPE_ID) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_STATUS_ID_2CATEGORY_FK FOREIGN KEY (SUPPLIER_STATUS_ID) REFERENCES CONFIG_CATEGORY(CATEGORY_ID)
go

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_CONTACT_ID_2CONTACT_FK FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID)
go

ALTER TABLE COMPANY ADD CONSTRAINT COMPANY_PK PRIMARY KEY(COMP_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_PK PRIMARY KEY(ORGU_ID)
go

ALTER TABLE PRGP_TYPE ADD CONSTRAINT PRGP_TYPE_PK PRIMARY KEY(PRGT_ID)
go

ALTER TABLE PRODGP_STRUCTURE ADD CONSTRAINT PRODGP_STRUCTURE_PK PRIMARY KEY(PSTR_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PK PRIMARY KEY(PGSD_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_PK PRIMARY KEY(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PK PRIMARY KEY(PGSL_ID)
go

ALTER TABLE ORG_TYPE ADD CONSTRAINT ORG_TYPE_PK PRIMARY KEY(ORGT_TYPE_ID)
go


ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_COMP_ID_2COMPANY_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY(COMP_ID)
go

ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_ORGT_TYPE_ID_2ORG_TYPE_FK FOREIGN KEY (ORGT_TYPE_ID) REFERENCES ORG_TYPE(ORGT_TYPE_ID)
go

ALTER TABLE PRODGP_STRUCTURE ADD CONSTRAINT PRODGP_STRUCTURE_ORGU_ID_2ORG_UNIT_FK FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PSTR_ID_2PRODGP_STRUCTURE_FK FOREIGN KEY (PSTR_ID) REFERENCES PRODGP_STRUCTURE(PSTR_ID)
go

ALTER TABLE PRODGP_STRUCTURE_DETAIL ADD CONSTRAINT PRODGP_STRUCTURE_DETAIL_PRGT_ID_2PRGP_TYPE_FK FOREIGN KEY (PRGT_ID) REFERENCES PRGP_TYPE(PRGT_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_ORGU_ID_2ORG_UNIT_FK FOREIGN KEY (ORGU_ID) REFERENCES ORG_UNIT(ORGU_ID)
go

ALTER TABLE PRODUCT_GROUP ADD CONSTRAINT PRODUCT_GROUP_PRGT_ID_2PRGP_TYPE_FK FOREIGN KEY (PRGT_ID) REFERENCES PRGP_TYPE(PRGT_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PSTR_ID_2PRODGP_STRUCTURE_FK FOREIGN KEY (PSTR_ID) REFERENCES PRODGP_STRUCTURE(PSTR_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_PARENT_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_PARENT_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PRGP_CHILD_ID_2PRODUCT_GROUP_FK FOREIGN KEY (PRGP_CHILD_ID) REFERENCES PRODUCT_GROUP(PRGP_ID)
go

ALTER TABLE PRODGP_STR_LINK ADD CONSTRAINT PRODGP_STR_LINK_PGSD_ID_2PRODGP_STRUCTURE_DETAIL_FK FOREIGN KEY (PGSD_ID) REFERENCES PRODGP_STRUCTURE_DETAIL(PGSD_ID)
go
